"""Ordinary sentences from this repository's own docs, for the benign measurement.

S4.4 round 5 (2026-09-23), harness v4 part (c): every sentence here goes
through the commit gate and the import check, and the refusals are counted
against v0.16.0 and pinned in test_legacy_credential_check.py.

How it was built, once, by a script (not at test time): git-tracked Markdown
under docs/ plus README.md at commit 6c24a97, code fences and tables
skipped, emphasis, backticks and heading or quote marks stripped, sentences
of 6 to 60 words, duplicates dropped, then one sentence in every 33 of
the 13270 kept. No sentence was edited or chosen by hand, except
that an em dash became a comma. Nothing here is a credential; some
sentences are about credentials, because the docs are.
"""

from __future__ import annotations

DOC_SENTENCES: tuple[str, ...] = (
    'The continuity layer for AI agents.',
    'Hermes is opt-in: add --host hermes.',
    'This is the verb for ordinary memory, including when the user has not asked the agent to remember.',
    'endpoint are not part of the current product.',
    'Do not claim SQLite or other reduced local modes as supported public runtimes unless they preserve Alice\u2019s continuity, retrieval, and correction semantics without special-case behavior.',
    'preserve explicit imported provenance with source_kind = openclaw_import',
    'Normalize all importer provenance into one unprefixed schema immediately',
    'Alice must not become a generic notes app, Obsidian clone, or chatbot with memory.',
    'Keep architecture clean enough for open-source contributors.',
    'User can set default domain and sensitivity for each connector.',
    'Must produce candidate memories for meaningful new insights.',
    'Option to save answer as artifact.',
    'Sprint 2 , Capture, Archive, Normalize',
    'Non-technical user can capture, review, ask, and read briefs.',
    'The next version of Alice should make one thing undeniable:',
    'Ask the agent something it should need memory for.',
    'context_depth and budget_strategy are fields on the context-pack',
    'audit , with outcomes and audit guarantees per verb is documented in the',
    "When a key carries --project-scope, the resolved identity's project scope",
    'project-domain memories within their project scope;',
    'The JSONL contains sensitive plaintext. 0600 limits local file access but',
    'Portable backups include active sources and chunks, memories and fact keys,',
    'This includes extension comments that would',
    'DATABASE_ADMIN_URL runs migrations, verification, and pg_restore as',
    'Next: produce a brief with source references.',
    'Workflow orchestrator: request open-loop context, create new open loops for blocked work.',
    'Agent integrations declare identity on the same tool.',
    'Use this checklist after a fresh clone.',
    'Agent keys do not replace TLS or',
    'Do not apply those templates to active rows and do not blindly delete',
    'For the Alice Hermes memory provider, bridge_mode: auto or bridge_mode: assist',
    'restricted by default: health, family, spiritual, legal, financial, regulated',
    'generic thread, approval, task, and trace histories are client-bounded, but their list endpoints do not yet provide cursor pagination',
    'tools against a local SQLite file.',
    'thread inputs are accepted for compatibility and reported in',
    'memories, open loops, and sources with supporting evidence. projects,',
    'Salience comes from the query surface only.',
    'Explicit "remember this" instructions go through alice_memory_commit, and',
    'The legacy surface requires Postgres: on the SQLite backend the legacy',
    'trusted memory changes only after human review',
    'This is the canonical local setup walkthrough for Alice.',
    'Semantic search uses any OpenAI-compatible embeddings endpoint (Ollama, LM Studio, OpenAI).',
    'Set ALICE_USER_ID to the local Alice user UUID.',
    'role-separated test below verifies the surviving audit skeleton and proves that',
    'MCP servers bound with ALICE_AGENT_API_KEY expose only the core surface; legacy handlers fail closed because they do not all implement the same persisted-target authorization contract',
    'This folder preserves superseded planning and control material removed from the live docs during Context Compaction 01.',
    'Telegram uses secret_ref values or the local secret provider instead of raw token settings.',
    'browser clipper is still bookmarklet/local-endpoint MVP',
    'Add stronger local alpha health checks.',
    'Improve the dogfooding dashboard so it is useful for daily review.',
    'Local folder config/status/sync/watch use the new settings/state model.',
    'prepare Postgres or verify existing Postgres',
    'Document secure access through SSH tunnel.',
    'Agents such as Hermes and OpenClaw may continue using MCP/API/CLI as primary access paths. /vnext should show what agents did, what Alice generated, what policies blocked or filtered, and what needs human review.',
    'Accepted memory appears in later context packs.',
    'Agent memory proposals link to Memory Review.',
    'Doctor/Readiness status is visible in /vnext.',
    'Telegram messages should create sources like:',
    'Candidate memory is generated with provenance.',
    'No trusted memory is mutated without review.',
    'Full deterministic generators for remaining scheduler workflows',
    'Postgres-backed smoke test covers daemon/due-run behavior.',
    'Model provider abstraction exists and supports deterministic/mock and at least one real provider path.',
    'ADD / UPDATE / SUPERSEDE / DELETE / NOOP',
    'Reduce local startup and onboarding friction without semantic drift.',
    'The goal is usage proof, feedback quality, and credible launch readiness rather than broad admin or governance buildout.',
    'Hermes and OpenClaw have polished, documented, tested Alice paths',
    'first-party packs are versioned and documented',
    'They described internal closeout procedures for an older Phase 2 sprint 14',
    'send item to review or triage',
    'benefits from explicit support for memory and executive function',
    'resumption brief generation must be deterministic for a fixed input state',
    'deterministic review-action workflow for open loops:',
    'scoped filters (thread, task, project, person, time window)',
    'avoid schema churn unrelated to continuity objects',
    'Without this, the chief-of-staff cannot improve or accurately supervise follow-through.',
    'Convert chief-of-staff recommendations into deterministic, approval-bounded handoff artifacts that can plug into existing governed workflows.',
    'The phase fails if handoffs are only decorative exports that do not materially reduce the user\u2019s execution burden.',
    'This sprint has two major workstreams:',
    'Create a ready-to-use Hermes skill/instruction file.',
    'Alice stores output as source or reviewable artifact',
    'Alice records who acted, what permission profile was used, which filters were applied, which actions were blocked, and which generated artifacts require review.',
    'Restricted domains and high-sensitivity classes are filtered or blocked by policy.',
    'The live workspace payload and UI now expose recent trusted memory commits and inline confirmations in Agent Activity.',
    'environment secret references such as env:TELEGRAM_BOT_TOKEN',
    'This phase makes Alice vNext practically installable from GitHub on a headless Ubuntu box for Hermes dogfood testing.',
    'The live workspace payload now includes:',
    'Decide how much of /vnext should become live-write UI for connector configuration versus CLI-first operator controls.',
    'Focused local-runtime unit tests: 37 passed.',
    '/vnext Model Comparison And Review Controls',
    'Hermes and OpenClaw copy-paste skill packs',
    'Added append-only event-log helpers with deterministic hashing.',
    'Added visible domain and sensitivity labels across generated artifacts and review rows.',
    '/.venv/bin/python -m pytest tests/unit -q: 1057 passed',
    'Label extraction: a response is correct iff "yes" appears in the',
    '(25/30 \u2192 22/30): CoT makes the model more willing to answer when memory',
    'GOLD-VALUE (gold present; gold wins same-sentence ties, matching the',
    'The other two rows should be re-generated with complete receipts',
    'Shared by both runs: gpt-4o generation at temperature 0,',
    'SQLite FTS5 + vector cosine fused with reciprocal-rank fusion, budget',
    'Overall accuracy: 64.6% (323/500) , run 2026-07-05 at commit eda49da',
    'query-shape-aware aggregation mode is the planned next step, and improving',
    'the documented memory cost), but end-to-end recall at very large corpora',
    'rules, truncation counts, and a deterministic digest.',
    "Keep the raw value in the owner's secret manager and revoke it when its",
    'A reference host prepares it as follows:',
    'alicebot_app, and its service environment must never contain any privileged',
    'alicebot_backup is NOSUPERUSER NOCREATEDB NOCREATEROLE BYPASSRLS; it',
    'This changes the baseline for every future database created from template1.',
    'attest runtime DB role=alicebot_app for both the PostgreSQL session and',
    'Remote /v1 is unsupported until those routes have application',
    'the archive, encrypt it before upload, keep an off-host encrypted copy, apply a',
    'record the current release tag/SHA and migration head;',
    'public_dns=true and public_ca=true after an external TLS probe;',
    'The baseline report is evidence, not aspiration.',
    'These examples show the narrow default adoption path for a generic external agent: call Alice one time through POST /v1/continuity/brief, then use the returned bundle inside your runtime.',
    'Export ignores SQLite-reserved sqlite_stat tables created by ANALYZE,',
    'semantic evidence without a spurious digest mismatch.',
    'and fail closed at 16,384 rows instead of doubling forever.',
    'Assistant and governed-request drafts are keyed to the selected thread and',
    'A fresh isolated pass-6 build produced a 1,110,095-byte wheel with SHA-256',
    'The Desloppify full-profile scan used isolated state under /tmp.',
    'No builder created a commit, pushed, tagged, published,',
    'Retrieval pushes hard project/people/time constraints before LIMIT across',
    'Review immutable published migration 0084 plus new migrations 0085 and',
    'truth, release-static, isolated package verification, and diff checks.',
    'range-valid, and reconcile with ranks/aggregates; known corpus digests and',
    'CI/check set on that exact SHA, perform fresh external control readback and',
    'Candidate form: remediation remains uncommitted; there is no final candidate',
    'JSON; invalid expected workflow identities; and timestamp/freshness drift.',
    'RELEASING.md accurately distinguishes operator readback from authenticated',
    "against the clean candidate's exact SHA before publication.",
    'Create an intentional candidate commit on the remediation branch and record',
    'persistence remains a separate best-effort step.',
    'credentialed workflow, modify live repository controls, or publish a package.',
    'Batch 11 was frozen before review returned one finding.',
    'coverage.json and uv.lock are excluded because they were pre-existing,',
    'PASS again on the updated documentation carrier.',
    'Release check: PASS (alice-memory 0.10.3); no checksum artifact was written',
    'Control documents enforce the historical Batch 8 versus current Batch 9',
    'Unresolved non-null supersession pointers in either direction fail before',
    'The first full-unit preflight exposed one obsolete test expectation that',
    'The persisted-source PostgreSQL resolver and migration 0090 now choose',
    'build 1.5.0, isolated setuptools 80.9.0, and wheel 0.45.1 were byte-identical.',
    'results whose JSON type is string.',
    'across workspace, wheel, and sdist; evergreen description and handoff',
    'nested agentic_memory.next_action) and every recursive event-payload string',
    'wheel and sdist smokes passed in 13.82 and 15.48 seconds, seven-file archive',
    'opened_at DESC, then created_at DESC, then id DESC.',
    'Twine passed in 0.29 seconds, release-check passed in 0.17 seconds, isolated',
    'CAS, no re-embed loop, and signed vector participation.',
    'REQUIRED on one documentation-truth P3; production CAS semantics approved.',
    'The ordinary proof still checks exact artifact/revision/event linkage and',
    'OpenAPI: 82 test_main tests passed; 294 operations covered by 49 exact,',
    'resolver tier, full-envelope scope_json, actual duplicate recapture, and',
    'vNext coverage shard: 3 files / 13 tests passed; 80.69%',
    'The Refreeze 7 carrier freeze repeated every readback below on its then-current',
    'Combined statement/branch coverage was 49,500/65,365 (75.7286%);',
    'using exact SOURCE_DATE_EPOCH=1784096425; snapshot manifest SHA-256 was',
    'The second Refreeze 17 review found one final activation bypass: the first',
    'left unstaged and uncommitted for independent review; its delivery-state',
    'branch, the receipt requires the exact pair 0.10.4/0.10.4; missing,',
    'correction itself is intentionally uncommitted for review.',
    'chr() table from migration 0090, including U+001C\u2013U+001F, NEL, and NBSP,',
    'redaction carries only the supported content-free skeleton, repeated rows',
    'finite mathematically integral numbers, and the explicit boolean scalar',
    'Confirm 0090 is the sole new Alembic head and its source-dedupe survivor',
    'a canonical release-engineer sequence and evidence wording that match',
    'existence, and current project state are intentionally excluded from the',
    'Historical Builder Repair Batch 9 review deltas (superseded)',
    'Batch 10 closes only those findings:',
    'migration dedupe identity retain Python/SQLite parity.',
    'Two focused regressions, the complete 256-test MCP file, and',
    'The fake open-loop list must order by opened_at DESC,',
    ',332 units with coverage floors and all 463 role-separated PostgreSQL',
    'Preserve the immutable v0.10.3 release notes/checksums and historical tag.',
    'require-main-head, and --require-clean; read back and attest the',
    'failure, the guard was narrowed to full-history ancestry proof plus an always-',
    'hosted workspace isolation, migrations 0088 and 0090.',
    'The third independent review pass found five bounded parity and evidence gaps.',
    'Historical Builder Repair Batch 6 closure (superseded)',
    'and redacted accepted/rejected replay remains admissible.',
    'bounded findings; historical Batch 8/9/10 evidence does not approve the',
    'Independent review returned changes required on exactly these bounded P2s:',
    'test, activates this receipt and all finalization markers.',
    'release notes and checksums were not edited.',
    'that correction found one final activation bypass: matching wrong versions',
    'Its subsequent independent review returned changes required on exactly',
    'The same ASCII-only case folding, exact',
    'files are recorded green and were corroborated by the static/control',
    'SQLite surface for the fifth-audit findings.',
    'must fail closed rather than resurrecting it.',
    'find_live_memory_by_canonical_text: repeats the non-empty check and',
    'Only 34 of those 102 advertised key sets match; 68 have phantom or missing',
    'but leading-slash URL resolution discards them for every requestJson',
    'Project identity: substantially broader than the original three-word',
    'Lock and validate the terminal artifact and collect all',
    'The corrected source-specific resolver is used by:',
    'historical because its independent review returned changes required.',
    'next-action metadata, and relevant event payload text. _vnext_resume',
    'Two focused regressions, the complete 256-test MCP file, and 3,328 full units',
    'SQLite list_open_loops and list_open_loop_events row-field admission;',
    'the locked row before a signed vector is written; and',
    'Active handoff-directory presence now activates finalization markers and the',
    'flag is import/start-time and requires process restart, and that providers',
    'mutation guards against stale repair-ledger, Phase-2-active, and extraction-',
    'fixtures created isolated databases and migrated from the immutable chain to',
    'omit the dead production S3 override errors and the health endpoint echo while',
    'The exact 14-module/12-TypedDict/model-pack public-name guards, the dead',
    'A core-only production process must boot without S3_ACCESS_KEY and',
    'Phase 2 starts in a later,',
    'The Phase 1 sign-off deviations are now dispositioned without opening Phase 2:',
    'had incomplete nested action/trust records and nullable optional scope keys.',
    'deliverable and is absent from this carrier.',
    'three required new production modules, omit removed modules, and preserve',
    'Telegram or stores a Telegram bot token: the dedicated route requires supplied updates,',
    'and polymorphic justification gates must pass in both modes.',
    'The standalone alicebot_worker.main.run() task executor is also disabled unless',
    'Provider endpoints require that prior bootstrap and fail clearly when it is absent.',
    'provider runtime, default/legacy surfaces, and a Removed Legacy Surfaces appendix.',
    'LongMemEval and the provider-free negative control, complete legacy-on and',
    'documentation-truth correction, the focused control suite passed 79/79 and',
    'normalized sdist compared byte-identical across dist-a and dist-b:',
    'PENDING FINAL APPROVAL: the independent reviewer had marked the included',
    'Generic search_memories and alice_recall FTS/websearch retrieval',
    'Terminal replay uses one bounded store call but preserves the complete',
    'package-manager major, TypeScript, Next ESLint, or Node types requires a',
    'Phase 3 begins only under its own brief.',
    'FIX_MATRIX.md , item-by-item closure of 2.0 through 2.14 and the associated',
    'declares its required feature floor; release-body decoding is type-checked;',
    'APPROVED for Phase 2 handoff to the release engineer.',
    'Terminal project-update replay uses one target-filtered store lookup with',
    'role-separated PostgreSQL 16.13/pgvector 0.8.2 passed 399 legacy-on',
    'apply and verify the prepared MainProtect required-check update;',
    'MCP, CLI, scheduler, and diagnostic carriers',
    'legacy MCP review/correct/forget variants when enabled;',
    'Application, PostgreSQL constraints, migration normalization, and SQLite',
    'memory-operation, MCP, CLI, and releasing docs describe the actual Phase 2',
    'LongMemEval tests, seven checked evidence-replay arms, and two focused',
    'A deletion records the six-digit base mode.',
    'PostgreSQL and SQLite store extraction is paired; generated SQL text,',
    'Tag only that approved SHA, create the GitHub Release, publish to PyPI, and',
    'ENGINEER_HANDOFF.md , review order, invariants, reproduction commands,',
    'attestation, CodeQL, tagging, GitHub Release creation, or PyPI publication has',
    'store.py, vnext_store.py, mcp_tools.py, cli, contracts.py, and',
    'passed and is the authoritative result.',
    'The facade preserves imports and consumer behavior.',
    'package build, publication, or repository-setting mutation was performed.',
    "file's current modification belongs to that owner lane, not Sprint 4.",
    'is preserved; cadence changes no selection behavior.',
    'Sprint 4.2 benchmark closure is NO-GO.',
    'This is not a live dirty-tree',
    'nonzero while answer sufficiency is unearned.',
    'I did not review, edit, hash, test, approve, or add any of them to the',
    'OWNER GATE OPEN: no real-host deployment receipt.',
    'Gitleaks scans the entire c9d2424..HEAD PR range.',
    'Use these trailers with values computed from the',
    'COMMITTED-SHA CI GATE OPEN: the old receipt 4cf7e08b... and commit',
    'shallow-clone proofs run, a fresh receipt is minted, and the delta receives',
    'has been reproduced in both full-history and depth-1/no-tag scratch commits.',
    'repository virtual environment, with an isolated fail-on-old test.',
    'tests; shallow truth plus ops passed 42 with 3 deliberate history-only',
    'The reviewed v3 carrier is committed at',
    'workspace bootstrap to return 404 not_found until the row exists.',
    'corrections and one migration module docstring; its post-correction focused',
    'is required for an already-stamped database because its end state is',
    'Review the control-document tests against pending and published release',
    'setup, dump flags, seed helper, validators, or tests because those parts form',
    'scripts/seed_local_user.py helper is shared by the installer and the manual',
    'v0.14.0 Deployment Guide Fixes v4 Independent Review Report',
    'No tag contains 0093, and the latest published release remains',
    'available, the exact recorded base tree remains mandatory.',
    'requires exactly one matching public-schema ACL entry and fails closed when',
    'dependency-free target: 6 passed, including the in-file mutation guard;',
    'final ops unit focus: 53 passed;',
    'after migrations, use separate admin, app, backup, and lifecycle credentials,',
    'default user scope comes from ALICEBOT_AUTH_USER_ID',
    'error_code with a static companion message',
    'B2 auto-capture pipeline for sync_turn: alice_capture_candidates then alice_commit_captures',
    'sync_turn_capture_enabled (bool, default false; when omitted, an explicitly configured bridge_mode: assist or bridge_mode: auto enables sync_turn capture)',
    'Skills: decision policy and workflow instructions (when to call tools, how to format output, what evidence to include).',
    'Fetch review queue or detail with alice_memory_review.',
    'a server bound with ALICE_AGENT_API_KEY hides and rejects every legacy tool.',
    'The other eight core tools become listed',
    'For first-run memory expectations and a deterministic way to prove memory',
    'explicitly want deprecated persisted task-adaptive briefing output',
    'Hosted session bearer tokens and model packs are not part of this boundary.',
    'X-AliceBot-User-Id (or ALICEBOT_AUTH_USER_ID), not a hosted bearer session.',
    'key management: alicebot agent keys create --agent-id <id> --profile <profile>',
    "Suggested guardrails so this doesn't repeat:",
    'tokens, passwords) in any field, or split across fields \u2192 rejected.',
    'Commits accept an idempotency_key; retries replay the original result',
    'credential material and the response carries text_withheld: true.',
    'or entity_id on the Postgres backend)',
    'an edited revision plus an agent.memory_expired /',
    'six numeric rating dimensions (usefulness, accuracy, source_grounding,',
    'persisted trust-signal rows for contradiction, correction, corroboration, and weak inference',
    'Each nonzero category ships with an explicit action string so the operator can decide what to inspect next.',
    'At least one active agent API key exists.',
    '"Addressed to the agent" is decided by the subject of the clause, not by',
    "row's end is never read against its own start.",
    '("begin by rotating the private key /certificate pair") is not read at all:',
    'rationale, source refs and project scope.',
    'Prod DB password: over a body Kd9xoYWu83nq, the same title without the',
    'A NAME=value line with a real secret',
    'transcript shape relayed under an internal source_type promotes.',
    'does not refuse them: an instruction-shaped note that the ordinary commit',
    'new files (eval/longmemeval/, scripts/run_longmemeval.py, this page);',
    'paragraph per turn, session id + date in the header, title, and',
    'seconds each, roughly 30\u201360 minutes total on a laptop.',
    'promotion is store-level (update_memory), not a bypass of the write',
    'domains pattern; bind project_scope to agent API keys (closes the',
    'Full Zep/Graphiti-parity bi-temporal graph , XL; the M slice above covers',
    'That command starts the MCP server against a local SQLite file, exposes the',
    'The vector-scale work re-examined the sqlite-vec rejection with evidence.',
    '[ ] release runbook and tag plan are present and coherent',
    'People/time scope predicates are pushed into the',
    "external audit's findings, but its protected semantic release gate failed on a",
    'The PyPI publish job now installs the package',
    'Artifact promotion creates its memory target',
    'online-safe concurrent indexes with invalid-index retry).',
    'operator can never inspect one workspace while mutating another.',
    'All 294 operations carry contracts derived from',
    'RELEASING.md and the v0.10.4 handoff records).',
    'by default; no destructive migration is part of this cut.',
    'Surviving HTTP handlers return stable detail.code and detail.message',
    'The operation also cannot retroactively erase upstream source systems,',
    'check/MainProtect readback, release identity, tag, GitHub Release, and PyPI',
    'threshold that previously applied to the monolith.',
    'per-query blob streaming that dominated large-corpus recall: the vector',
    'reviewed (two independent review rounds each for the vector cache and its',
    'The documented backup dump role could not dump this schema at all: every',
    'A second brain that does not make you approve everything, and a credential',
    'it a report; and a localiser distinguishes an instruction about a product from',
    'And the credential guard is now a strict superset, catching',
    'loopback, and importers stop following links out of the directory you chose.',
    'Dependency advisories fixed rather than excepted',
    'Both new regression tests were checked by reverting each fix and confirming',
    'Every link in this release points at the new location.',
    'this published release with no agent key and no environment variables:',
    'Every core tool accepts an agent identity',
    'not ship still resolves exactly as before, and only a shadowing copy of a',
    'mid-line, as in "ticket #42", is not a heading.',
    'This also restores what the tool already promised. alice_capture says it keeps',
    'Three independent causes, each sufficient on its own:',
    'An oversized paragraph now splits on its own lines before falling back to',
    'A .mcpb manifest is generated only when',
    'query when budget_strategy is left at default. pack_view is',
    'target branch: main after squash-merge of codex/release-r1-v0-2-0-readiness',
    '[ ] docs/quickstart/local-setup-and-first-result.md matches the shipped Alice Lite path',
    'Local secret-provider abstraction for environment references and encrypted local fallback storage, with redaction before connector payloads reach source metadata or event logs.',
    'hosted SLA or managed cloud launch',
    'make setup now creates .env and .env.lite when missing.',
    'Scheduler bootstrap no longer crashes on live Postgres stores: the',
    'Expired facts (valid_to < now) excluded from search by default; stale',
    'Some lifecycle operations also check a',
    'revision trigger while backfilling an existing data-bearing database.',
    'Install the exact v0.9.2 artifact only after it is published and its hash',
    'Content dedupe is now scope-aware , the content',
    'in docs/release/v0.9.4-checksums.txt by the post-publication commit.',
    '[x] ./.venv/bin/python -c \'from alicebot_api.cli import main; raise SystemExit(main(["eval", "run", "--suite", "all"]))\'',
    'FTS-only coverage probe was not scored, the scored baseline already used',
    'for that arm was not on the current main lineage.',
    'Phase 12 retrieval now runs as an explicit hybrid pipeline instead of a single opaque ranking pass.',
    'copied into Alice and kept MIT: the patent grant and NOTICE obligations travel',
    'effect here with the same semantics as the Postgres path.',
    'times token saving from filtering before fetching.',
    'This runbook restores one self-hosted, single-tenant Alice installation.',
    'Restrict its login source, protect and rotate it, monitor',
    'If the checkpoint reports busy, do not copy just the main file.',
    'Upgrade v0.12.0 to current in the restored',
    'A scheduler is stuck when it reports that it should be running but either:',
    'enough sample when adjudicated sample >= 20',
    'The command exits 0 only when',
    'P14-S1 through P14-S5 are all shipped.',
    'The script extracts v0.12.0, runs the v0.12.0 code and migration head, seeds a',
    'Do not downgrade the partially migrated database in place.',
    'Missing connector_settings or connector_state: run ./scripts/migrate.sh, then alicebot vnext doctor --fix-safe.',
    'Stage A evidence ledger , scope, source provenance,',
    'The one-time browser-clipper capability is scoped to its capture endpoint,',
    'It passed on the frozen carrier alongside tests proving',
    'can select different transitive versions over time.',
    'This retained target is not a current release requirement.',
    "the repository's full release matrix for the exact carrier.",
    'hostile PostgreSQL strings across strict, match-any, source, and scoped paths,',
    'bound to one user and normalized web origin.',
    'True redaction scrubs governed content from durable memories and coupled',
    'Deferred Finding: Directory Import Source Integrity',
    'claims, protection from a compromised host/root account, and the security of',
    "The store runs under the user's RLS",
    'by a fail-closed install-tree audit in CI.',
    'Treat generated artifacts as reviewable drafts until explicitly accepted.',
    'Procedural memory: typed end to end.',
    'connector OAuth, packaged browser extensions, hosted connector polling, cloud',
    'Raw input arrives from manual capture, import, or connector payload.',
    'Decisions are allowed, allowed_with_filtering, requires_review, or blocked; filtered and blocked outcomes are logged.',
    'transcription execution, hosted connector polling, hosted scheduling, and',
    'returns a structured refusal and the cluster falls back to dedup , the',
    'every reviewed input, promotes the candidate, and then executes exactly',
    'docs corrections that match current commands',
)

# The sentences that use credential vocabulary (password, token, secret, API
# key, private key, credential, ssh-, sk-, BEGIN, Bearer, AKIA, _KEY, key= or
# key:), from the same 13270: all 474 that matched. These are
# where a credential check refuses honest text.
CREDENTIAL_VOCABULARY_SENTENCES: tuple[str, ...] = (
    'All legacy tools require a deliberately keyless local-operator deployment; a server bound with ALICE_AGENT_API_KEY exposes only the enabled core set.',
    'Custom agents calling the HTTP API authenticate with per-agent API keys.',
    'each importer must persist a source-specific deterministic dedupe key in provenance (<source>_dedupe_key)',
    'Must not exceed configured token budget.',
    'Secrets stored in OS keychain or encrypted local secret store.',
    'No secrets or private data in repo.',
    'headless Ubuntu install path for SSH-only dogfood hosts',
    'a key with alicebot agent keys create and set ALICE_AGENT_API_KEY',
    'and leave ALICE_AGENT_API_KEY unset; payload identity is honored and',
    'When the request sets max_tokens, a greedy packer drops lowest-priority',
    'reports serialized_token_estimate. allocation covers memories, loops,',
    'the unique-content budget. max_tokens is therefore not a transport cap.',
    'The compact MCP result reports serialized_token_estimate for that exact',
    'full_pack_excluded_token_estimate) rather than presenting it as the size of',
    'filled after reranking; max_items and the token-budget packer still',
    'scored, whether anything actually reordered, latency, and token usage.',
    'The moment at least one active key exists, every protected /v0/vnext request requires Authorization: Bearer alice_sk_..., including requests that omit agent identity fields.',
    'MCP servers bind a key by setting ALICE_AGENT_API_KEY in the server env.',
    'but the shared safety checks (secret screening, explicit intent, source',
    'On HTTP, once any agent API key exists for the user, commits that declare',
    'On MCP, set ALICE_AGENT_API_KEY in the server environment to bind the',
    'They intentionally omit users, agent API keys,',
    'rotate and protect its credential, and use it only for backups.',
    'alternative avoids a stored backup credential, but it applies only when the',
    'Using libpq environment variables keeps the credentialed DSN out of process',
    'Protect the environment and unset PGPASSWORD after the command.',
    'alicebot_drill credential could create arbitrary databases and exhaust',
    'Restrict its login source, protect and rotate the credential,',
    'If a subprocess fails, the command writes bounded, credential-scrubbed',
    'workflow receipt is sanitized and excludes database URLs, secrets, paths, and',
    'The alice_vnext_ examples below are keyless-local legacy compatibility only and require ALICE_MCP_LEGACY_TOOLS=1; a server bound with ALICE_AGENT_API_KEY hides and rejects them.',
    'no secret value appears in output',
    'redacted connector config, never secret values',
    'neither the reusable agent key nor a configured capture_token.',
    'Do not install them for new setups; they predate the v0.6.0 overhaul (hybrid retrieval, consolidated core MCP surface, per-agent API keys).',
    'If remote access is required, first provision and test agent API keys,',
    'page origin and one capture; it is not a general remote-access credential.',
    'generated local database passwords are not printed',
    'Store real connector secrets through the',
    'configured secret-provider path, and pass only secret_ref identifiers through',
    'Do not rename it, and make sure both role passwords match the',
    'credentials in DATABASE_URL / DATABASE_ADMIN_URL before migrating.',
    'By default, uninstall only stops/removes services and preserves repo, config, secrets, local data, and database.',
    'Local compose password mismatch after changing DATABASE_URL:',
    'Do not paste real database passwords into shared logs.',
    'ALICE_AGENT_API_KEY to this server: key-bound MCP hides and rejects the',
    'A server bound with ALICE_AGENT_API_KEY hides and rejects them.',
    'context_depth (and budget_strategy for token budgets) are fields on',
    'no managed Gmail OAuth consent/account-linking flow; manual operator-token',
    'no managed Calendar OAuth consent/account-linking flow; manual operator-token',
    'secrets fallback is alpha-grade unless OS or managed secret provider is configured',
    'agent API keys cannot be created (alicebot agent keys create requires Postgres); leave ALICE_AGENT_API_KEY unset , agent identity is still honored and audited as unauthenticated_local, while a set key fails closed and rejects every write',
    'users, agent identities/API keys, embedding vectors, and soft-deleted rows are not portable; fact keys and entity relationship history are included, while nullable references to omitted rows are cleared and graph edges with omitted known endpoints are excluded so the portable set remains foreign-key closed',
    'Accepts the same memory_types filter, and max_tokens budgets each',
    'a tight token budget is spent (balanced | facts_first |',
    'ALICE_AGENT_API_KEY in the server env to a key created with',
    'on-ramp mode, leave ALICE_AGENT_API_KEY unset; payload identity is',
    'ignored while ALICE_AGENT_API_KEY is set, and direct legacy calls fail',
    'over source chunks and memories, where any token variant counts as',
    'Do not include secrets, private source exports, or customer data.',
    'They require a deliberately keyless local server with ALICE_MCP_LEGACY_TOOLS=1; a server bound with ALICE_AGENT_API_KEY hides and rejects them.',
    'context_depth (and budget_strategy for max_tokens packing) are',
    'every /v0/vnext request requires Bearer authentication, including requests from the review',
    'Unbound admin_agent API key, and select Use key for this session.',
    'page origin; the reusable agent key and any configured capture_token remain in trusted clients.',
    'a fresh local-keyless user with zero active agent keys, leaving ALICE_AGENT_API_KEY unset; or',
    'an active, unbound admin_agent key for that same user, exported as ALICE_AGENT_API_KEY.',
    'active key exists, omitting the Bearer header also fails closed.',
    'process arguments, never the raw key:',
    'Do not paste customer or production secrets into a demo.',
    'Unbound admin_agent API key, and inspect the accepted row in Memory Review.',
    'the /vnext browser-memory Bearer, so they must not be presented as live keyed',
    'Once any active agent API key exists for a user, protected /v0/vnext requests',
    'connector secrets should be stored as secret refs',
    'CLI/API/UI/event/source/artifact output should not print secret values',
    'all /v0/vnext HTTP routes share one authentication boundary: keyless local compatibility ends when the user creates an active key, after which strict Bearer authentication is required',
    'the local /vnext console accepts an unbound trusted_local_agent or admin_agent key only through its password field, keeps it only in browser memory for the mounted session, and forwards it only to loopback /v0/vnext routes; it never reads the key from environment variables, local storage, URLs, logs, or errors',
    'the browser-clipper bookmarklet never embeds or prompts for an agent key or a reusable capture_token; a trusted Alice UI issues a short-lived, origin-bound, one-time capture capability, while trusted non-browser API clients may use Bearer authentication plus capture_token',
    'MCP servers bound with ALICE_AGENT_API_KEY expose only the core surface; legacy handlers fail closed because they do not all implement the same persisted-target authorization contract',
    'include command output with secrets redacted',
    'do not include private exports, real Telegram payloads, API tokens, or personal datasets',
    'Never paste secret values into bug reports.',
    'added vNext secret-provider abstraction with environment references, encrypted local fallback storage, in-memory tests, and redaction helpers',
    'hardened Telegram sync with secret references, retries, allowlist rejection logging, and safe cursor advancement',
    'hardened browser clipper with optional local capture-token enforcement and token redaction before persistence',
    'added live /vnext connector configuration for Telegram, local folder, and browser clipper defaults, sync actions, status, counters, failures, and secret presence',
    'production deployments should wire the new secret-provider interface to OS keychain or managed secret infrastructure instead of relying on the local encrypted-file alpha fallback',
    'Telegram uses secret_ref values or the local secret provider instead of raw token settings.',
    'Browser clipper can enforce a local capture token and redacts it before persistence.',
    'CLI/API/UI/event/source/artifact paths expose configured posture, not secret values.',
    'the local encrypted secret file is an alpha fallback; production use should connect the same interface to OS keychain or managed secret infrastructure',
    'covered by unit tests, integration tests, web lint/build, migration status, connector-hardening smoke, secret-redaction smoke, dogfood-doctor smoke, live-capture smoke, capture-to-brief smoke, agentic-scheduler smoke, and evals',
    'yes, updated vNext architecture to include dedicated connector settings/state storage, local secret references, and connector cursor reliability',
    'Alice vNext Sprint Prompt: Dogfood Hardening + Connector Settings/Secrets',
    'connector config/secrets/cursors are not yet cleanly separated into dedicated storage',
    'Telegram bot token handling needs local secret hardening',
    'state changes must not leak secrets',
    'Add a local secret storage abstraction for connector secrets.',
    'browser clipper local token if implemented',
    'Implement a secret store abstraction that can support:',
    'The actual secret value should not be returned by API/CLI/UI.',
    'Telegram connector uses secret_ref, not raw token storage.',
    'Secrets never appear in event logs.',
    'Secrets never appear in connector health.',
    'Secrets never appear in API responses.',
    'Secrets never appear in web UI.',
    'CLI can set/update/test Telegram token without printing it.',
    'optional local capture token status if implemented',
    '/vnext can configure Telegram without exposing token.',
    'bookmarklet generator with local endpoint URL and optional token',
    'optional capture token supported or clearly planned',
    'User configures Telegram secret_ref and allowed chat IDs.',
    'Doctor reports migration status, connector settings, secret store, scheduler status, and capture pipeline health.',
    'Telegram uses secret_ref and no raw bot token is stored in logs/API/UI.',
    'Local secret store abstraction exists with test/mock provider and local fallback or env-ref support.',
    'vNext Doctor exists and detects migration/config/secret/scheduler/capture health issues.',
    'Doctor/alpha check do not expose secrets.',
    'Secrets are never printed in install logs.',
    'Alice vNext now has a hardened local dogfood loop with live capture connectors, dedicated connector settings/state tables, secret references, doctor checks, scheduler runtime, model-backed Brain workflows, quality ratings, and dogfooding telemetry.',
    'The previous phase specifically hardened connector settings/state, secret references, doctor checks, live connector configuration, and dogfooding telemetry.',
    'Doctor output does not expose secrets.',
    'Secret values are never displayed in UI/API/logs.',
    'bot token configuration through local secrets/config',
    'Secrets are not stored in plaintext logs or event payloads.',
    'Telegram bot token must be secret-managed.',
    'All failures are logged without leaking secrets.',
    'token budgeting and provider/model-pack briefing defaults',
    'pack compatibility must remain declarative through compatibility.provider_keys and compatibility.runtime_providers',
    'release guidance begins at the repository README and the',
    'secrets fallback is alpha-grade unless OS/managed secret provider is configured',
    'Included memory_key in project update revisions.',
    'A policy engine that evaluates agent identity, permission profile, domain, sensitivity, source type, confidence, contradiction refs, project scope, and unsafe secret markers before any write.',
    'Rejection for read-only agents, out-of-scope project agents, unsafe secret storage, missing explicit intent, and policy-blocked writes.',
    'We added a vNext secret-provider layer with:',
    'environment secret references such as env:TELEGRAM_BOT_TOKEN',
    'redaction helpers for secret-like fields before persistence',
    'Telegram and browser clipper now use secret_ref values instead of returning or persisting raw token values.',
    'CLI/API/UI/health/event/source paths expose configured/not-configured posture, not secret content.',
    'preserve raw evidence while redacting secret fields',
    'enforce browser clipper capture tokens when configured',
    'The doctor checks required vNext tables, default connector settings/state rows, Telegram secret references, scheduler daemon posture, connector failures, and recommended fixes.',
    'health counters, cursor state, failures, secret presence, and sync mode',
    'The bookmarklet flow now prompts for the local endpoint, user ID, optional token, and note, then captures URL/title/selection/page text into the local API.',
    'The payload path supports capture-token enforcement and redacts the token before source/event persistence.',
    'We added the dogfood daily checklist and updated vNext docs, quickstart, local runtime, security/privacy, CLI integration, release notes, release checklist, README, and control reports to reflect the hardened connector settings/state/secret posture.',
    'Secret handling is materially safer: connector tokens are references, not normal config values.',
    'The encrypted local secret file is an alpha fallback; production deployments should use the same interface with OS keychain or managed secret infrastructure.',
    'The installer does not print generated local database passwords or connector secrets.',
    'Secrets remain referenced/redacted, not exposed in UI/API payloads.',
    'Live Telegram capture: configurable token reference, allowlisted chat IDs, getUpdates sync, rejected-chat isolation, cursor tracking, failure logging, and CLI/API status surfaces.',
    'Move connector config, secrets, and cursors from event-log-backed config into a dedicated settings table and encrypted local secret store when hardening for non-developer use.',
    'Fixed project update revision persistence by including the required memory_key.',
    'Connector auth and polling: turn deterministic payload ingestion into real connector flows with secret/cursor storage.',
    'Call shape: one user message, temperature=0, max_tokens=10.',
    'require no API keys and re-derive from committed files; identical inputs',
    'The 24k-char context roughly doubles the token spend of the baseline',
    'No API keys required to check any of it.',
    'tokens instead of ~3k) scored 49.2% , a directional +4\u20137 point lift',
    'Roughly 35 minutes total; no network or API keys required.',
    'Each brief records its mode, explicit strategy, token budget, section selection',
    'deployment-time environment/secret injection, scheduled encrypted backups,',
    "Keep the raw value in the owner's secret manager and revoke it when its",
    'because Alice needs the HTTP Authorization header for its own Bearer agent',
    'manager must replace ${ALICEBOT_DB_APP_PASSWORD} while rendering an',
    'The two environment files contain credentials and are readable only by root',
    'certificates are public trust anchors, not private keys, but root ownership',
    'Never store a CA private key or a client private key',
    'Before substitution, percent-encode each database password as URL userinfo',
    'the password value, not the complete DSN, and keep the raw and encoded values',
    'unique runtime, migration, backup, and lifecycle database passwords injected',
    'Connector and model credentials are separate secret-manager injections.',
    'the surviving Telegram connector, inject TELEGRAM_BOT_TOKEN into the service',
    'Do not commit a raw connector token or put provider API keys in',
    'identifier; the environment value it resolves is the secret.',
    'provider keys, connector tokens, or other secrets in this file.',
    'and the web API helper permits that Bearer key only for loopback or the exact',
    'https://evil.example, plaintext remote origins, credentials, and base paths.',
    "/v0; the server cannot use the browser-memory Bearer key or the browser's mTLS",
    'and rotate its credential and restrict its network access.',
    'alicebot_drill credential could create arbitrary databases and consume disk.',
    'A passwordless peer URL does not work',
    'verify the server and certificate without putting a credentialed URL in',
    "owner's secret manager, confirm alicebot agent keys list shows an active key",
    'Run unset ALICE_AGENT_API_KEY immediately afterward if the deployment shell',
    'and client private keys outside the repository.',
    'job must use secret-manager injection, create a custom-format pg_dump, verify',
    'documented retention policy, and emit a secret-free success/failure signal.',
    'IP addresses, DSNs, credentials, agent keys or prefixes, certificate paths,',
    'Unknown suite_key filters fail fast instead of silently falling back to a partial run.',
    'A dedicated protected-environment workflow produces a credential-free,',
    'Its closed credentialless JSON binds the exact repository,',
    'seeding signatures must match, and credential-bearing keys and values are',
    'permanent v1 flag by binding a closed credentialless claim to the exact',
    'Publication separately consumes a credentialless structured repository',
    'releases, trusted publishing, credential controls, and exact-SHA checks.',
    'Never put endpoints, tokens, credentials, or account identifiers in',
    'Do not put credentials in workflow YAML,',
    'retrieval query; report/attestation digests match; and recursive credential',
    'push, merge, tag, workflow dispatch, credential handling, release, or',
    'trusted publishing with no long-lived PyPI credential;',
    "are read-only except for the publish job's required id-token: write.",
    'live settings inspection, documents the closed credentialless contract, and',
    'real configured provider and PostgreSQL/pgvector; inspect the credential-',
    'token for omitted legacy inserts, and fences raw configuration updates.',
    'reads, DNS, secret resolution, or adapter selection.',
    'endpoint addresses before commit, require credentials compatible with Azure',
    'auth-mode changes, retire replaced secrets only after reference checks, and',
    'credentialed workflow, modify live repository controls, or publish a package.',
    'implementations, retrieval admission and shared source consumers, API-key',
    'Python, SQLite, PostgreSQL, migration 0090, and API-key policy',
    'invocation drops it and sends the stored sentinel as a Bearer token.',
    'reject core-only production configuration when S3 credentials are absent or',
    'Web Telegram configuration is on-demand allowlist-only; secret-ref,',
    'Ubuntu packaging no longer advertises a bot token, Telegram secret, or',
    'secret, webhook, and delivery paths must stay absent or rejected before side',
    'Historical config must not expose unknown top-level token/poll keys.',
    'not advertise bot-token or webhook-secret configuration.',
    'session, device, membership-administration, or bearer-auth seams.',
    'A core-only production process must boot without S3_ACCESS_KEY and',
    'Phase 3 router/store restructuring did not begin.',
    'validator no longer require dead S3 credentials.',
    'allowlisted raw-source ingestion with no polling, delivery, token, or secret',
    'publish, begin Phase 2, or claim completion of the external release gates.',
    'no longer require dead S3 credentials.',
    'working tree is delivered uncommitted and does not begin Phase 2.',
    'Telegram or stores a Telegram bot token: the dedicated route requires supplied updates,',
    'has no token/secret-ref/polling/interval controls, and exposes no empty-update action that',
    'handlers use X-AliceBot-User-Id or ALICEBOT_AUTH_USER_ID, never hosted bearer',
    'S3_ACCESS_KEY and S3_SECRET_KEY are not production requirements because no S3',
    'production .env without S3 credentials, while existing auth/database/CORS failures',
    'by vnext_connectors.py; polling/token resolution is removed.',
    'idempotent replay, telemetry, and target hardening without bearer sessions/model packs.',
    'A null/blank project-update memory_key must fail before any reject-side',
    'Phase 3 begins only under its own brief.',
    'ALICE_AGENT_API_KEY, then runs only the default-surface smoke.',
    'FTS/tokenized retrieval and vector search are separate arms and are not',
    'Reject now validates a nonblank candidate memory_key before any mutation,',
    'It clears dedupe_key only on live',
    'simple-request transport, and recursive secret redaction across PostgreSQL',
    'Stage A threat-model, authorization, input-validation, secret-handling, and',
    'tokens rather than trusting URL substrings.',
    'separate backup and lifecycle credentials, and persistent /etc/alicebot',
    'keys, root-credential confinement, role capabilities and probes, command',
    'carrier: an admin RLS capability, a root credential in an unprivileged step,',
    'Subprocess failures emit bounded, credential-scrubbed diagnostics only to',
    'Diagnostics, database URLs, credentials, fixture text, and local paths',
    'after migrations, use separate admin, app, backup, and lifecycle credentials,',
    'bootstrap, rotate and protect the four database credentials, and complete one',
    'Agent HTTP calls authenticate with per-agent API keys:',
    'Agents send it as Authorization: Bearer $ALICE_AGENT_API_KEY; MCP binds a key through the ALICE_AGENT_API_KEY environment variable.',
    'Secret values are never printed; the CLI stores or resolves only secret_ref values.',
    'vNext scheduler, connector-hardening, secret-redaction, doctor, and model-backed smoke output is JSON and fails nonzero if any gate fails',
    'Hermes server, set ALICE_AGENT_API_KEY to an issued key; do not enable the',
    'legacy_config_keys: legacy keys still accepted for compatibility',
    'Optional: mcp_<alice_server>_alice_recent_changes (keyless-local legacy tool; unavailable when the Alice MCP server is bound with ALICE_AGENT_API_KEY)',
    'a server bound with ALICE_AGENT_API_KEY hides and rejects every legacy tool.',
    'ALICE_EMBEDDINGS_API_KEY , enable semantic vector search in',
    'Provider credentials are stored as secret references and never returned in',
    'Hosted session bearer tokens and model packs are not part of this boundary.',
    'Provider test records capability and invocation telemetry without secrets.',
    'No model-pack field or hosted bearer-session requirement appears in the',
    'X-AliceBot-User-Id (or ALICEBOT_AUTH_USER_ID), not a hosted bearer session.',
    'Existing providers with the same provider_key and display_name are left in place.',
    'For bearer-auth OpenAI-compatible providers, send api_key when rotating credentials.',
    'Alice supplies memory tools authenticated with per-agent API keys.',
    'dependency) calling /v0/vnext with Authorization: Bearer alice_sk_...',
    'The installer/setup path now pins pnpm, creates .env.lite, validates env files before sourcing, quotes values with spaces, defaults the local Ubuntu template to development mode, requires the repo venv, and aligns Docker Compose Postgres credentials with the active Alice env.',
    'DB credential mismatch with docker compose defaults:',
    'env had custom DB passwords, but docker-compose.yml starts Postgres',
    'make migrate then fails with repeated password authentication failed for',
    'Fix: either align .env credentials with compose defaults for local mode,',
    'or make compose use env-provided credentials consistently.',
    'Blocked policy, a read-only caller, or secret-looking content (API keys,',
    'tokens, passwords) in any field, or split across fields \u2192 rejected.',
    'per-agent API keys exist, identity is resolved and enforced from the key',
    'record , on HTTP via Authorization: Bearer alice_sk_..., on MCP via',
    'Commits accept an idempotency_key; retries replay the original result',
    'bundle with a max_tokens budget and a token_report of what was dropped)',
    'sources_first , how the token budget is spent).',
    'New text that carries credential material is refused on both surfaces and',
    'or summary carries credential material, or whose approval reason does, and',
    'move one into, active or accepted while its text carries credential',
    'If the reason carries credential material, the',
    'it carried credential material instead, and the response carries',
    'carries credential material: it is replaced by text withheld: it carried',
    'credential material and the response carries text_withheld: true.',
    'whose new text, whose pending text, or whose rationale carries credential',
    'rationale, or canonical_text, carrying credential material is stored as a',
    'Expire always completes: a reason carrying credential material is',
    'stored as rationale withheld: it carried credential material and the',
    "refused when the memory's text, or the reason, carries credential material.",
    'structured keys such as fact_key, fact_value, preference_key, preference_value, and temporal bounds',
    'requires you to issue an agent API key.',
    'At least one active agent API key exists.',
    'No hard floor rule fires: credential material, agent-directed instructions,',
    'One credential rule, one check on the write paths',
    'The write paths below all call one check, carries_credential_material in',
    "Alice's own alice_sk_ agent key), private key material (below), Bearer",
    'with an opaque token, a JWT, a password inside a URL, "the password for X is <value>",',
    'and a NAME=value line whose name is a secret name and whose value looks',
    'So {"api_key": "<key>"} in a body is caught,',
    'while structural keys such as fact_key, dedupe_key or next_page_token',
    'Private key material: recall wins over precision.',
    'the dashed, case-exact armor line of a private key on its own, anywhere in',
    'a field, whatever surrounds it: five dashes, BEGIN, an optional RSA,',
    'EC, DSA, OPENSSH or ENCRYPTED, PRIVATE KEY, five dashes; and the',
    'same line for a PGP PRIVATE KEY BLOCK.',
    'PRIVATE KEY (or PRIVATE KEY BLOCK) header',
    'the commit door leaves of them, and refused when they start a private key',
    'SSH_PRIVATE_KEY_B64=, a file wrapped at any width).',
    'A private key is the most dangerous thing to store and the rarest to',
    '("begin by rotating the private key /certificate pair") is not read at all:',
    'each unencrypted and passphrase-encrypted; traditional and PKCS#8 RSA and',
    'EC, including an encrypted RSA key; two OpenPGP secret keys from GnuPG; and',
    'SSH_PRIVATE_KEY_B64= or wrapped at 40, 44, 64 or 76 characters, at the',
    'Not refused: SSH public keys since 2026-09-23 (ssh-ed25519, ssh-rsa,',
    'alone or after a label such as "Deploy key:"; a PEM public key, a',
    "Since 2026-09-23 the promotion floor's credential clause calls the same check",
    'A credential in a reason, rationale',
    'under a key name an AWS secret access key and a plain password are not',
    'The root cause, a name rule that counts any _key',
    'as a secret name, is a follow-up ticket; once it lands, key and value',
    'Prod DB password: over a body Kd9xoYWu83nq, the same title without the',
    'colon, API_KEY= over a value, Authorization: Bearer over a token, a',
    'prose split (a title "The vault password" over a body that starts with',
    '"is" and then the password), and a fact_key/value structured body all',
    'a backup by hand can put Deploy token: ghp_ in a summary and the rest of',
    'Config shapes no rule reads. machine host login user password X',
    '(netrc), aws configure set aws_secret_access_key X, curl -u user:X,',
    'Authorization: Basic all pass (pinned in test_private_key_recall.py).',
    'An INI or YAML line with the secret name and = or : is caught.',
    'read case-exact, as Slack issues them; an upper-cased token passes.',
    'user and password, Authorization: Token <hex>, a lower-case bearer,',
    'mysql -p<password>, docker login -p, a JSON "pass" field, wallet seed',
    'phrases, 0x private keys, Azure SAS tokens and connection strings, Twilio,',
    'Discord and Telegram bot tokens, and any high-entropy string with no',
    'prefix and no secret name next to it.',
    'A NAME=value line with a real secret',
    'name and a password-shaped value is refused even in documentation, so',
    'are refused (owner ruling: no allow-list of toy passwords).',
    'portal password: Changed after the phishing scare.", "Password:',
    'see-vault", "Secret: Launch2027PlanB", BUILD_KEY=v2026.09.1, the jwt.io',
    'sample token, AKIAIOSFODNN7EXAMPLE, upper-case coincidences such as',
    'SEE ASIA over PACIFICTEAMNOTES..., and password = hash_password(pw)',
    "ending on a bare floor verb and a field beginning with that verb's object",
    'credential instead of trying to read intent out of the sentence, and the',
    'credential material is refused on the write paths listed under "What is',
    'still catches credentials and agent-directed instructions whatever the',
    'review, and several write paths did not check credentials at all.',
    'Scale: _s \u2248 40\u201350 sessions (~115k tokens) per question; _m \u2248 500',
    'sessions (~1.5M tokens); oracle = evidence sessions only.',
    'overlap, under a character budget (default 12,000 chars \u2248 3k tokens).',
    'Current Date = question_date, temperature=0, max_tokens=500;',
    'abstention split, retrieval stats (context chars/\u2248tokens, retrieval-latency',
    'Generation + judging with hosted models: 500 \u00d7 (one ~3\u20134k-token',
    'generation + one ~300-token judge call).',
    'deterministic and reported via context_chars / approx_context_tokens,',
    'Truth fixes: enforce max_tokens with greedy budget packing; honor or',
    'domains pattern; bind project_scope to agent API keys (closes the',
    '(SQLiteVNextStore: FTS5 with a porter tokenizer and',
    'credential-free semantic-eval attestation validation runs against the',
    'ownership uses a stable identity token, failed one-shot runs exit nonzero,',
    'token, schedule delivery, or mount a channel product.',
    'URLs, and CORS deployment settings, but no longer requires S3_ACCESS_KEY or',
    'stamp token on every embedding write, clear, and redaction) removes the',
    'The receipt contains no hostnames, addresses, credentials, or paths.',
    'Documented secret paths moved from boot-volatile locations to persistent',
    'A second brain that does not make you approve everything, and a credential',
    'also fixes a live defect in the credential guard that was rejecting ordinary',
    'Some content always requires review regardless of who wrote it: credential',
    'instruction-shaped, and several write paths did not check credentials at',
    'Credential material is refused on the write paths listed in',
    'Credential detection, corrected in both directions',
    'The guard that refuses to store secrets was wrong twice over, and both halves',
    'It matched credential names as bare substrings, so private key matched inside',
    'private keyboard and any note discussing api_key rotation was rejected',
    'SECRET_KEY= was caught while AWS_SECRET_ACCESS_KEY=, OPENAI_API_KEY=,',
    'most ordinary way a live credential reaches a note, went straight through.',
    'A credential is now a secret-shaped name assigned an actual value.',
    'And the credential guard is now a strict superset, catching',
    'nineteen credential shapes where the previous release caught twelve, with no',
    'sweep by key, and the floor still refuses credentials and agent-directed',
    'memory commit did refuse a credential in a single field.',
    'A credential value that is entirely lowercase letters, carries no digit, and',
    'identity middleware returned early for every path that did not begin with',
    'Once the bound user has provisioned an agent API key, every /v1 request must',
    'entire document. estimate_item_tokens JSON-dumps the item to price it, so',
    'a 235KB source was charged roughly 59k tokens against a 50k ceiling, was',
    'the last brief token estimate, and candidates waiting last.',
    'Local secret-provider abstraction for environment references and encrypted local fallback storage, with redaction before connector payloads reach source metadata or event logs.',
    'Local dogfood readiness checks through alicebot vnext migrations status, alicebot vnext doctor, and connector-hardening/secret-redaction/doctor/operator-console smokes.',
    'The local encrypted secret store is an alpha fallback; production deployments should wire the same secret-provider interface to OS keychain or managed secret infrastructure.',
    'The installer preserves existing config and does not overwrite secrets.',
    'Generated local database passwords are not printed.',
    'Docker Compose Postgres credentials can be driven from the active Alice env.',
    'The Postgres init role script creates or updates the app role with the configured password.',
    'All vNext agent HTTP endpoints accept Authorization: Bearer alice_sk_...;',
    'The MCP server binds a key via the ALICE_AGENT_API_KEY environment variable.',
    '(adds retrieval columns/indexes, agent_api_keys, and the scheduler',
    'To authenticate agents, create keys and pass them as Bearer tokens; nothing',
    'max_tokens is enforced with greedy budget packing; packs report',
    'backfill; filters everywhere; agent API keys can bind a project scope ,',
    'Service limits are authoritative: at most 50 requested items, 50,000 tokens,',
    'mode is loopback-only; hosted bearer panels separately allow validated HTTPS.',
    'URLs/errors are credential-safe, request deadlines are endpoint-specific,',
    '[x] Security/privacy docs describe connector boundaries and secret handling.',
    '[x] Connector secrets use references and local encrypted/env-backed providers without exposing raw values.',
    '[x] Local doctor checks report missing migrations, missing connector rows, secret reference problems, scheduler posture, and capture failures.',
    '[x] Real Postgres secret-redaction smoke check.',
    '[x] No secrets, private exports, real personal data, or production credentials are committed.',
    '[x] Connector settings/state storage and secret references have security review notes.',
    'Real Postgres secret-redaction smoke passed for Telegram token absence, browser token absence, and redacted capture-token evidence.',
    'lexical: BM25-style token overlap across continuity titles, body fields, and provenance',
    'Track 3: progressive disclosure and token accounting',
    'times token saving from filtering before fetching.',
    'Report token cost as a first-class field on retrieval responses, so a caller',
    "A measured, reproducible token saving on Alice's own eval",
    'compromised lifecycle credential could create arbitrary databases and exhaust',
    'credential-scrubbed stderr to the process stderr under its stable failure code.',
    'environment variables so credentials do not appear in process arguments.',
    'protect and rotate its credential, and do not use it for migrations or restore.',
    'Unix socket avoids a stored backup credential.',
    'Never record credentials or memory content in the recovery receipt.',
    'No API keys or running Postgres instance are required for this unit-contract',
    'contains no paths, DSNs, credentials, or memory content.',
    'Do not paste a credentialed URL into a transcript or command line.',
    'The stamp query must return exactly one row with id = 1 and a nonempty token.',
    'Opening/bootstraping the same unchanged store again must preserve that token.',
    'Browser clipper unauthorized: prepare a fresh one-time bookmarklet in the authenticated Alice console and confirm that its bound origin matches the page; trusted API clients may instead send Bearer authentication plus the configured local capture_token.',
    'No token value belongs in event logs, source metadata, artifact metadata, CLI output, API responses, or UI state.',
    'Secrets and redaction , key storage, provider secrets,',
    '; the browser-clipper credential-context remediation belongs to the Phase 5',
    'Keyless local-owner mode: while a user has zero active agent API keys,',
    'requests require a valid Authorization: Bearer alice_sk_... key.',
    'A key-bound server uses ALICE_AGENT_API_KEY; payload identity cannot replace',
    'vNext operation reaches the central boundary and rejects a missing credential',
    'Can agent keys, provider/connector credentials, database URLs, or sensitive',
    'environment/reproducibility gap before beginning substantive review.',
    'future external review is commissioned, its non-secret receipt should contain',
    'Do not commit exploit details or live secrets to the public',
    'SQLite FTS5 query builders quote normalized tokens rather than accepting raw',
    'Secrets, Keys, Logging, And Redaction Evidence',
    'Current provider registration stages credentials in the local provider secret',
    'Secret-shaped fields are recursively replaced with before',
    'URL validation rejects embedded credentials and disallowed local/private',
    'provider configurations onto the current secret-reference path.',
    'configured credential is observed at the stub transport and proven absent from',
    'secrets, key issuance/revocation, and host/proxy/firewall configuration.',
    'filesystem, or provenance behavior; an external provider exfiltrating secrets',
    'credential disclosure to a realistic remote attacker.',
    'Update this model whenever an external surface, credential type, deployment',
    'capture, hardened connector settings/state/secrets, agent-facing context packs',
    'polling/token ownership), generic agent-output ingestion, dedicated settings/state rows, local encrypted',
    'secret references, retry/cursor hardening, plus deterministic PDF, DOCX, CSV,',
    'Agent-originated HTTP calls authenticate with per-agent API keys.',
    'Create one with alicebot agent keys create --agent-id <id> --profile <profile> and send it as Authorization: Bearer <key>.',
    'MCP binds a key through the ALICE_AGENT_API_KEY environment variable.',
    'endpoint; Alice does not poll Telegram or manage a bot token',
    'Connector secrets are represented by secret_ref values and resolved through the secret-provider interface, not returned as normal settings.',
    'The connector settings/state/secret posture is local-alpha infrastructure.',
    'should bind the secret-provider interface to OS keychain or managed secret',
    'instances share no anchor token ("kitchen items replaced" =',
    'The /vnext Home, Inbox, Trace, Doctor, and Connectors surfaces also show dogfooding and capture health: captures by connector, captures today/week, candidate memory creation, source review/archive posture, capture-to-brief traceability, doctor readiness, artifact ratings, useful-insight feedback, connector enabled/configured state, persisted settings, secret presence, cursors, dedupe, failures, and last sync posture.',
    'no polling, token ownership, or scheduled delivery)',
    'The secret-redaction smoke verifies that browser clipper capture tokens never appear in persisted source/event output.',
    'The dogfood-doctor smoke verifies migration readiness, default connector rows, scheduler posture, configured secret references, and blocking failure counts.',
    'Do not commit secrets, tokens, real personal exports, private chats, production credentials, or unredacted customer data.',
    'Connector secrets are referenced, not returned.',
    'surviving local connectors may use secret_ref values.',
    'stored through the secret-provider abstraction, with an encrypted local file',
    'Trusted API clients may use a configured browser-clipper capture token, which is redacted from source/event evidence.',
    'The future OS keychain or hosted secret-provider implementation should satisfy the same interface without changing connector behavior.',
    'Inspect new fixtures for secrets and personal data.',
    'Confirm alicebot vnext smoke connector-hardening, alicebot vnext smoke secret-redaction, and alicebot vnext smoke dogfood-doctor pass against the local Postgres database.',
)
