"""THROWAWAY TEST KEYS. Not real credentials, never used for anything.

Generated once on 2026-09-23 for the credential floor tests (S4.4 round 2,
addendum F4) with ssh-keygen (ed25519, rsa 2048, ecdsa P-256, each
unencrypted and passphrase-encrypted with the passphrase
"throwaway-passphrase") and openssl (RSA 2048 and EC P-256, traditional and
PKCS#8, plus encrypted RSA). Two OpenPGP secret keys (ed25519, and RSA 2048
exported with a Comment armor header) and one OpenPGP public key were added
the same day with GnuPG, in an isolated GNUPGHOME under a scratch directory
and never a real keyring. Two PuTTY PPK files (v2 RSA and v3 ed25519) were
added in S4.4 round 3: puttygen is not installed and nothing was downloaded,
so they were built from the throwaway OpenSSH RSA and ed25519 keys above per
the documented PPK format (header, Encryption, Comment, Public-Lines with the
public blob, Private-Lines with the private blob, Private-MAC computed as
PuTTY does for an unencrypted file). They are structurally faithful, not
puttygen output. The rest exist so the tests read real key output rather
than a hand-made imitation of it.

Stored base64-encoded, never as raw PEM armor lines, so secret scanners do
not flag the repository. Decode with throwaway_key(name) at test time. Keys
are never generated at test time, so CI does not depend on ssh-keygen or gpg.
"""

from __future__ import annotations

import base64


_ENCODED: dict[str, str] = {
    "openssh_ecdsa": (
        "LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFF"
        "Ym05dVpRQUFBQUFBQUFBQkFBQUFhQUFBQUJObFkyUnpZUwoxemFHRXlMVzVwYzNSd01qVTJBQUFBQ0c1cGMzUndNalUyQUFB"
        "QVFRUk9tZXJaSlVUdGpwaUpHOGVPRVFza2xXWG9KQTBpCk11WTJUVmZCUUtWMHVRbW1mSmhISzlJVVBadEZiSVBTQ2JyK01a"
        "VmZKVGRxaXZkaStPWVJtK1BtQUFBQXNJempvdTZNNDYKTHVBQUFBRTJWalpITmhMWE5vWVRJdGJtbHpkSEF5TlRZQUFBQUli"
        "bWx6ZEhBeU5UWUFBQUJCQkU2WjZ0a2xSTzJPbUlrYgp4NDRSQ3lTVlplZ2tEU0l5NWpaTlY4RkFwWFM1Q2FaOG1FY3IwaFE5"
        "bTBWc2c5SUp1djR4bFY4bE4ycUs5Mkw0NWhHYjQrCllBQUFBaEFKODA3K1ZOUlBFTjFDanRQSTRxYTJEdlhGNDNKTFpBWVJH"
        "SVNxeFFtaEdJQUFBQUVuUm9jbTkzWVhkaGVTMTAKWlhOMExXdGxlUUVDQXdRRgotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUg"
        "S0VZLS0tLS0K"
    ),
    "openssh_ecdsa.pub": (
        "ZWNkc2Etc2hhMi1uaXN0cDI1NiBBQUFBRTJWalpITmhMWE5vWVRJdGJtbHpkSEF5TlRZQUFBQUlibWx6ZEhBeU5UWUFBQUJC"
        "QkU2WjZ0a2xSTzJPbUlrYng0NFJDeVNWWmVna0RTSXk1alpOVjhGQXBYUzVDYVo4bUVjcjBoUTltMFZzZzlJSnV2NHhsVjhs"
        "TjJxSzkyTDQ1aEdiNCtZPSB0aHJvd2F3YXktdGVzdC1rZXkK"
    ),
    "openssh_ecdsa_encrypted": (
        "LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQ21GbGN6STFOaTFq"
        "ZEhJQUFBQUdZbU55ZVhCMEFBQUFHQUFBQUJETkR4VFVnSApHc0hiNVZ2WVVib0dlL0FBQUFHQUFBQUFFQUFBQm9BQUFBRTJW"
        "alpITmhMWE5vWVRJdGJtbHpkSEF5TlRZQUFBQUlibWx6CmRIQXlOVFlBQUFCQkJDRFh5RzI2cXJDTnRmbkhLOE9ET0lkZW94"
        "Z2FwcmxETFNPTnRNNTRHVTdFUkdtRDhqMmk4OFpyNGkKSmpjMTJ0U0dld0R3YW14YWxHZE9xTk45MTJCMjhBQUFDd2orOGU2"
        "eWJRNGFGSStodnlzNTk5eG1Pc2poWWdlZzEvTExHbwp4RzJZZUcwbVVGRjNKS0RTcVNwc0NGcDlBRzJzbEd4bWYwQi9OOFZn"
        "M2hCOHY4MzF4aU41ZmE1bnBZT1VpczVRM2M5Q0lCCkVQeWoyc1NZNG1BZnZFUzluVTVvc0hMOGJIaDM0emdZbWZSRmhVRlhj"
        "WUcyd0lTODF5YU1LWksweDNaZnV2LzlhbzJ3aDYKaitUWjlUNk5pRXB1UkhpMWlrVDI0M1NWYTFWaHp4ZHdkbklIVjl4ck5O"
        "OFRyUnNmYUlnSUxTZ29lZms9Ci0tLS0tRU5EIE9QRU5TU0ggUFJJVkFURSBLRVktLS0tLQo="
    ),
    "openssh_ecdsa_encrypted.pub": (
        "ZWNkc2Etc2hhMi1uaXN0cDI1NiBBQUFBRTJWalpITmhMWE5vWVRJdGJtbHpkSEF5TlRZQUFBQUlibWx6ZEhBeU5UWUFBQUJC"
        "QkNEWHlHMjZxckNOdGZuSEs4T0RPSWRlb3hnYXBybERMU09OdE01NEdVN0VSR21EOGoyaTg4WnI0aUpqYzEydFNHZXdEd2Ft"
        "eGFsR2RPcU5OOTEyQjI4PSB0aHJvd2F3YXktdGVzdC1rZXkK"
    ),
    "openssh_ed25519": (
        "LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFF"
        "Ym05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNBL1JhelVFa1NSMEwzd2Jvb2h3R1l2VThS"
        "RFliU0ZkclRsUkY3TndWR25DQUFBQUppSGloN1FoNG9lCjBBQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQS9SYXpVRWtTUjBM"
        "M3dib29od0dZdlU4UkRZYlNGZHJUbFJGN053VkduQ0EKQUFBRUM0VUZXaUl3MDdjYTI2WHArbXQvc1R2Y1E2ejNidWZhcUty"
        "MHJ5ditRWjlEOUZyTlFTUkpIUXZmQnVpaUhBWmk5VAp4RU5odElWMnRPVkVYczNCVWFjSUFBQUFFblJvY205M1lYZGhlUzEw"
        "WlhOMExXdGxlUUVDQXc9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K"
    ),
    "openssh_ed25519.pub": (
        "c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUQ5RnJOUVNSSkhRdmZCdWlpSEFaaTlUeEVOaHRJVjJ0T1ZF"
        "WHMzQlVhY0kgdGhyb3dhd2F5LXRlc3Qta2V5Cg=="
    ),
    "openssh_ed25519_encrypted": (
        "LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQ21GbGN6STFOaTFq"
        "ZEhJQUFBQUdZbU55ZVhCMEFBQUFHQUFBQUJEaTRFZ1FoNApxWEx3TXhXRXA4Qk55bkFBQUFHQUFBQUFFQUFBQXpBQUFBQzNO"
        "emFDMWxaREkxTlRFNUFBQUFJTSt4STVEcVZpTHVuTXkwCndFd1dvb2gzZk5CZmNVMVZUY0lQUnhrOGxVbklBQUFBb0E4cFdy"
        "SmVyRzJIK1FkbEVtK3FCUi9nYTJYUVV6cUt6TVlPMksKeVhFSm5hOW95KzhmWUFTZkMxbFVuWjZnSWhTcmU0YWZCNmpKQk9K"
        "TUh3ZFBsZVZ3bDIrRk13cGdLVmNvbnh2UmFSd09seQp3eUdmZUovNjFja3QzbmNDaGNDeUpuUjYrUEpvYnljODdvYUhmUlRT"
        "ZC9HSkh4WElNZU1VSlNZL0xaWkVGSVhFUkxlZGFvCkdXeEFZMW9lRVEwbGxuc0JkaCtvT1d2Y0Q5MXdyTXZXaHRYQzA9Ci0t"
        "LS0tRU5EIE9QRU5TU0ggUFJJVkFURSBLRVktLS0tLQo="
    ),
    "openssh_ed25519_encrypted.pub": (
        "c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSU0reEk1RHFWaUx1bk15MHdFd1dvb2gzZk5CZmNVMVZUY0lQ"
        "UnhrOGxVbkkgdGhyb3dhd2F5LXRlc3Qta2V5Cg=="
    ),
    "openssh_rsa": (
        "LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFF"
        "Ym05dVpRQUFBQUFBQUFBQkFBQUJGd0FBQUFkemMyZ3RjbgpOaEFBQUFBd0VBQVFBQUFRRUFtMzcwaC9VcFVDMFYwalFqSW40"
        "ZlRRVHV5eEVoU0gyZnFDK29LeUhCWUswb2Q0SGRON3dqClhPVjg0RFVzM3FCaUI3QWN4WU9zSHJYdWdnMkRCQTYydFQ5aXlm"
        "Sm82NFZySm1xd0ViMyt5Wng5aGxUdGxlZ2NRNENNNUgKODA1NTh6UFhHRHA1VW0zbUpxZzRNblBMTzVWRE9QcU5GZ0R6NVY1"
        "OUFJL21vNjh2WWtHOHZqOFRkcHF2NGhIYnA4Q3lsaAoydTNwNng4UFluMldyVDlvcDNtUnVneldRWk1TQUFPb3E5U2FSNmpS"
        "bFJ6Ky9LdnZtNmJKcG95SDQxbS91TnZHRjFpVmVTCkhOUTBkRG5KMStxSGx3N2o5aTNXTHZ5emtEblZJd3ZNelBHVlpBNGJG"
        "RmlETGpIaXFEMG1hcDdoQnVpeEt1TTgyUmdkeDIKdjBpZThYQ0ZXUUFBQThncWhjOEtLb1hQQ2dBQUFBZHpjMmd0Y25OaEFB"
        "QUJBUUNiZnZTSDlTbFFMUlhTTkNNaWZoOU5CTwo3TEVTRklmWitvTDZnckljRmdyU2gzZ2QwM3ZDTmM1WHpnTlN6ZW9HSUhz"
        "QnpGZzZ3ZXRlNkNEWU1FRHJhMVAyTEo4bWpyCmhXc21hckFSdmY3Sm5IMkdWTzJWNkJ4RGdJemtmelRubnpNOWNZT25sU2Jl"
        "WW1xRGd5YzhzN2xVTTQrbzBXQVBQbFhuMEEKaithanJ5OWlRYnkrUHhOMm1xL2lFZHVud0xLV0hhN2Vuckh3OWlmWmF0UDJp"
        "bmVaRzZETlpCa3hJQUE2aXIxSnBIcU5HVgpIUDc4cSsrYnBzbW1qSWZqV2IrNDI4WVhXSlY1SWMxRFIwT2NuWDZvZVhEdVAy"
        "TGRZdS9MT1FPZFVqQzh6TThaVmtEaHNVCldJTXVNZUtvUFNacW51RUc2TEVxNHp6WkdCM0hhL1NKN3hjSVZaQUFBQUF3RUFB"
        "UUFBQVFBbk9ySktrcWxubHRoSWZlclgKU3VadXNlM2t3VithUUVkRlVUQ21JUS8rYWZFcHBWUEFPZkRhQVBPdVJQd2E5bStF"
        "N1FOMU9URDFWb1RqdnJEdEZ5RTFQTgphWmlGUzhCcDd2eEQ3RFd5R3FqNWFEaTIyZFFqL1BMK0ZiekZQMms0MkQxTjJZSytM"
        "d2UvZlBVZ2xXSVNtQ2VyZWxxWjBJCmUzdUV6bEZXamtwcy9ST1ZEQlNoVWg0SjZyL241Wkw4OUxlZ3pCbGRVNmZDUFlwdWFu"
        "cWhUTGdpNXlobWkxTWVYeEkxZ1UKQUU1dmpCWVhLaVRtRXozbEpPWGU1Zm9YZ2ZkQU9DcVdhckZRb0lWRWsyd3ZJSjIvcW5T"
        "cG9xRzRNZ3NjcmxDVlEvQnh3egpXUkFuaDVrVG9wTTVPQWtKeXpNV1BHQkVvczdtSS9PbWNJQ0orbUdyUytZQkFBQUFnUURE"
        "a0JQbmp0bnc5OTYyWTl2V1hSCktpNGU0OFRoKzNmUUJYZHhQaXJVdDNCcGNrSUdtS2l1MjFXRnpjckVjTmU5ZHRKenJDa2lS"
        "OEJ4M2owNE0rczEzYzdCcmkKazV5d0NEWVNYeS9pN3RIUUFLT29KTFBkOWtwV2tYODZsK2NWUEFQWlM4dmg0bWpJbWRGb0pH"
        "NnE0eHR5N1RZcUVSRS9sUwp2SSs4ZUZta0NzQ2dBQUFJRUF5Z2hPc2hvenRqR1JRb056UHNUQWZZeEhuL2s5QUhtQmhhandQ"
        "ZG1uSmJpWm9lR3YyejRlClFKd1JRdmFGVExLN0wwNldwRVIrc3NtNDY2S0ozZUp0VnFiWSsxd2N3blJmbmhpQURkZ2xYaVZn"
        "NXFMUHN2eUw5NFI0K2sKcHJxZEx4QktUSHN0U1ZnQ2RtaWloVUxHOUJVdGdoYWxqS0I4SkliRWI4ZStCMDhYa0FBQUNCQU1V"
        "SVVMdFhKR2xlOTduZAp5eFM3VUJRZ2c0TE81L1MrdWVsaFlXUG8zYVAzektXSDNwcm9ZbkN4T3hDZU90K0VqT3FYL1FZd1BU"
        "U3NOSjN1b1NCb0dICjBGOWFnYVRKYXBwYkhxMi83LzNKakJ5ZzVKYWNFWHpmaVRTVnA4ZkFsV0M0Q0tkTkhxaGhZanBiOTdI"
        "NU5OODhQRStxK2kKbkZSNjNIekNnb1VFc2hyaEFBQUFFblJvY205M1lYZGhlUzEwWlhOMExXdGxlUT09Ci0tLS0tRU5EIE9Q"
        "RU5TU0ggUFJJVkFURSBLRVktLS0tLQo="
    ),
    "openssh_rsa.pub": (
        "c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCQVFDYmZ2U0g5U2xRTFJYU05DTWlmaDlOQk83TEVTRklmWitv"
        "TDZnckljRmdyU2gzZ2QwM3ZDTmM1WHpnTlN6ZW9HSUhzQnpGZzZ3ZXRlNkNEWU1FRHJhMVAyTEo4bWpyaFdzbWFyQVJ2ZjdK"
        "bkgyR1ZPMlY2QnhEZ0l6a2Z6VG5uek05Y1lPbmxTYmVZbXFEZ3ljOHM3bFVNNCtvMFdBUFBsWG4wQWorYWpyeTlpUWJ5K1B4"
        "TjJtcS9pRWR1bndMS1dIYTdlbnJIdzlpZlphdFAyaW5lWkc2RE5aQmt4SUFBNmlyMUpwSHFOR1ZIUDc4cSsrYnBzbW1qSWZq"
        "V2IrNDI4WVhXSlY1SWMxRFIwT2NuWDZvZVhEdVAyTGRZdS9MT1FPZFVqQzh6TThaVmtEaHNVV0lNdU1lS29QU1pxbnVFRzZM"
        "RXE0enpaR0IzSGEvU0o3eGNJVlogdGhyb3dhd2F5LXRlc3Qta2V5Cg=="
    ),
    "openssh_rsa_encrypted": (
        "LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQ21GbGN6STFOaTFq"
        "ZEhJQUFBQUdZbU55ZVhCMEFBQUFHQUFBQUJDejNqQnFyMwphRzBsQlhhWlNCakUwbUFBQUFHQUFBQUFFQUFBRVhBQUFBQjNO"
        "emFDMXljMkVBQUFBREFRQUJBQUFCQVFEUlA5WkQrVXl1CnBEQS9RR0xBWEpCbmxYTEw2VWxGekZJUVd1WnQ3a0djdTFUaE1a"
        "NnFPWURsckJlTGVVRTBmRzdhZkxkbzJkNUxya2dMQ3cKaHRlQnBKNjVYTnZQYUhDRzhQcmV1Wlc5bElpc1d4UG5vQTU4dmpE"
        "dzBhMWtlOEdITGN4TGlJNVRwUkpEcHFPMGdnUzNlUwp5NUxTeC9Ed2VTVHJWbGRhS3EzYzVWVHphaVl4OUl6dWJJbmNWRTRY"
        "UVpFU0FEc1NKRkRLL0pnY2c1Vld3OXZBT0lFcnR2CmNLdHd5SEh1NTl4MXFLdXN0RmI3bVFvSHVwNXNXbTd3dVRZdEsvWEZl"
        "VVpLbzloNFozcTBSdERJbXRlUXdzNmd3Rlp3bVkKUDRUbDFJeE1pQVFCVjd3VHBiUmh5RDVCNEtJaUNGaVVUaUZibUJmemFJ"
        "cnJQdVN2bllHREFBQUQwRk8rM3kwRit6dTB3eQpJTVozM1hHeHF3Y1ZYYTJkRjg3VHkxRW43V0pCU3lzbkZKUDJZTm11M0xM"
        "S3dBeTFsZk5NQWUwT0EvQTBienNMbFlhMUJjCjBaT0NmYmRvSVJBbW5BWmkrN0VsK3RaRVRhYW5mcUNRTXp0akVSWWVEL0F1"
        "QzkvY0pXcE5aeVkyMkx3cVhSUUE1cElzOGsKQ1dicGN2SkRQVnpadGRtNCtUWnNvdnkvbmNiRFgxdzlnYXpsTXpnRjZrOWhD"
        "Sk92WGgyN282b3R2aXNTYTJOMUFHVHRMLwpQcmlMQmkzK0Z6eGhoWFpwS2luSzJmeFRoK0pPQW5qRisyQVhXeGNRa3VSL1Vm"
        "a3NobjErYlpSbE5TSVJSUDhZRzExRWpwCmplOSsvVHByNnkwQ1daeDRkRDhPZG8rY1dUSmRFRlZpQjlBdlhuZDl1c0NyYlJt"
        "azlOYXEzS0greDhhWG9OcVlmZWl3MWQKbUx3Y0dXcGw0cjBYbEl5MnBwdThaVzdUbXlEVTlxQVdDK0VtODcxZ280cWhSdVRr"
        "dHBBY3lpQmZZN3Q0dTFQYzY4bHN0YgpmNGs0NGMybjVXeExibFF1WEhrdGcwZm5jUU5nNmdlU2NRN280Q25EQ0dMN1JxTFNj"
        "NGVnNkUyOHN1Ukl4bENjMHRQSWtXCjZtRUIyTUdtQkdPd3Z6VHg5UWd5ZXVNQm1DR2xjYWcrUUVqbVVMWWhPMzJiem9IckNw"
        "Z2hueWZuQVMxcWxBUzhCcjMxbHoKWGtXL3ZLdEQzWGdDZzV4RE9hdVpSS1drMVYzR3U5Nkl4a0dqUXdUKzB3OXZwcFFWUlNX"
        "YW9ROFZyN3NMUHVsK3JKZXJBego2dlluZGNGaWwxSkI4Qk9Vb2VWNmVvVHFTQTlFUnlHc2tkaVVmT2RnNTVia1pLZE9hY1h0"
        "WVRhMEttdmpPbmhOMUJndjNQCmZsNElwMEhOMjR1ZnZ0VzN1bHloNXM3V1Rac1Q3aFgvYnhFVVFVR29zcExPdW5YRmRKWk9s"
        "WGZHTndNNkYyTzFBNVFxR3kKYjBnUHR5SXRGZHAyNW1ZY0lkVDFtV1R2UXpHR05BNGtCeW4wOGV0MHZ6VnpSajN5aEp2Sys2"
        "NmVOTGVCV3RKTUJVbXBuQQpvZ29Rc0hweFU0cTlBS0MvY3hpTnpnZksvNHVUSlpTZGNkREZGcU1CTDR5eitLTU5UVS9BZkFG"
        "L3VCbjJKTWJGSi9rdE5KCmlJZG4velYrb3JpY2hFZFZhMVNZUlQzTUh2SkdXVjJLN3lkVXA4VkVSRW1iZmJHeExVNmF6aFdN"
        "MXV2MGNaNDcySDhJbnIKZ1Z3UWNKZjIrb1d0SmJVNlZjOStsSGhtNWFuaW1GeHlwNTJYMEwrNTA2Y01raURET0hUVDVHTE9J"
        "U2tuUHpkU1pyOVZXTQpnUEhhZy9hWm9wNk43QkFDOW5mZVRaOFluTUYzZWpXUzBMMmxzUnFsM2tBU2ppdmloMnlVMEJIMkRy"
        "WjRxQmJaOEJMb3oyCnp4bi9GdTBqZ1BWWnpGREpOSTRITGs1WlJ2enJLTEd3cGs4OC9EODFkZHNVdzFEenU4dTRQeXh5T29G"
        "VURZeXFGSG91YTQKeDV5MHVEVFpZSlNYOTk0WWtGUGhIdGdXbSttRDNIRGYrL3QzTDF3OVlRalZYL0o3Y0RyZjhHWXBXU2U4"
        "ckd5V2orQ2hVaQo2eUtRVWVTMWdYRm9Lc01KenhYSk0yaHRLeE55bz0KLS0tLS1FTkQgT1BFTlNTSCBQUklWQVRFIEtFWS0t"
        "LS0tCg=="
    ),
    "openssh_rsa_encrypted.pub": (
        "c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCQVFEUlA5WkQrVXl1cERBL1FHTEFYSkJubFhMTDZVbEZ6RklR"
        "V3VadDdrR2N1MVRoTVo2cU9ZRGxyQmVMZVVFMGZHN2FmTGRvMmQ1THJrZ0xDd2h0ZUJwSjY1WE52UGFIQ0c4UHJldVpXOWxJ"
        "aXNXeFBub0E1OHZqRHcwYTFrZThHSExjeExpSTVUcFJKRHBxTzBnZ1MzZVN5NUxTeC9Ed2VTVHJWbGRhS3EzYzVWVHphaVl4"
        "OUl6dWJJbmNWRTRYUVpFU0FEc1NKRkRLL0pnY2c1Vld3OXZBT0lFcnR2Y0t0d3lISHU1OXgxcUt1c3RGYjdtUW9IdXA1c1dt"
        "N3d1VFl0Sy9YRmVVWktvOWg0WjNxMFJ0REltdGVRd3M2Z3dGWndtWVA0VGwxSXhNaUFRQlY3d1RwYlJoeUQ1QjRLSWlDRmlV"
        "VGlGYm1CZnphSXJyUHVTdm5ZR0QgdGhyb3dhd2F5LXRlc3Qta2V5Cg=="
    ),
    "pgp_ed25519.asc": (
        "LS0tLS1CRUdJTiBQR1AgUFJJVkFURSBLRVkgQkxPQ0stLS0tLQoKbEZnRWFyTmJheFlKS3dZQkJBSGFSdzhCQVFkQUJJKzF0"
        "VVVtNklaeVpDZEY3bEVUZzJLU3gzZlRNSnA3emNRVwp2NWljN0RZQUFRQ2paV1BrWFlkcm90SCszOUhnbCsvaXRmaUtaaGx0"
        "U2k5NURVNHhadmdleXhId3REUkJiR2xqClpTQlVhSEp2ZDJGM1lYa2dWR1Z6ZENCTFpYa2dQSFJvY205M1lYZGhlVUJsZUdG"
        "dGNHeGxMbWx1ZG1Gc2FXUSsKaUs4RUV4WUtBRmNXSVFSTmYyU1V1dlNFTHBqS3FXblpuc3RXWEN3SVlRVUNhck5iYXhzVWdB"
        "QUFBQUFFQUE1dApZVzUxTWl3eUxqVXJNUzR4TWl3d0xETUNHd01GQ3drSUJ3SUNJZ0lHRlFvSkNBc0NCQllDQXdFQ0hnY0NG"
        "NEFBCkNna1EyWjdMVmx3c0NHR0ovUUVBenhjcFZGUFFjSnRwMEREWmlUQ0IramkzWXIzTENtMStGOEZKczluOXovb0EKL2l3"
        "K1dBdGdkcVdSSmNyMWF5RWE5WFJPMHJRU2tnMmY5RGhLSlZMN2VZTUVuRjBFYXJOYmF4SUtLd1lCQkFHWApWUUVGQVFFSFFC"
        "MWxNeGVEVi9ueFpoSk8vWWcrdTlrNWR2dWNtL0IreDVOOEhiU3pTbUV4QXdFSUJ3QUEvMWRCCklWanFDK1pxYmJYeUowdVdr"
        "U3pPaTROZHBMK05rRmNwOUZWUGtydElFSlNJbEFRWUZnb0FQQlloQkUxL1pKUzYKOUlRdW1NcXBhZG1leTFaY0xBaGhCUUpx"
        "czF0ckd4U0FBQUFBQUFRQURtMWhiblV5TERJdU5Tc3hMakV5TERBcwpNd0liREFBS0NSRFpuc3RXWEN3SVlWOFVBUURLTy83"
        "bGxVZithVmZxWVdqZVRIME9uOWxtbE1jdGRBYXpBL0ZzCnY5MGZEUUQ3Qm5KR2RFdE41R3RObkNGSkdsNmg1aGNnZTM0RHBj"
        "Zllma09LQW5Da3JnWT0KPXp0bDUKLS0tLS1FTkQgUEdQIFBSSVZBVEUgS0VZIEJMT0NLLS0tLS0K"
    ),
    "pgp_ed25519_public.asc": (
        "LS0tLS1CRUdJTiBQR1AgUFVCTElDIEtFWSBCTE9DSy0tLS0tCgptRE1FYXJOYmF4WUpLd1lCQkFIYVJ3OEJBUWRBQkkrMXRV"
        "VW02SVp5WkNkRjdsRVRnMktTeDNmVE1KcDd6Y1FXCnY1aWM3RGEwTkVGc2FXTmxJRlJvY205M1lYZGhlU0JVWlhOMElFdGxl"
        "U0E4ZEdoeWIzZGhkMkY1UUdWNFlXMXcKYkdVdWFXNTJZV3hwWkQ2SXJ3UVRGZ29BVnhZaEJFMS9aSlM2OUlRdW1NcXBhZG1l"
        "eTFaY0xBaGhCUUpxczF0cgpHeFNBQUFBQUFBUUFEbTFoYm5VeUxESXVOU3N4TGpFeUxEQXNNd0liQXdVTENRZ0hBZ0lpQWdZ"
        "VkNna0lDd0lFCkZnSURBUUllQndJWGdBQUtDUkRabnN0V1hDd0lZWW45QVFEUEZ5bFVVOUJ3bTJuUU1ObUpNSUg2T0xkaXZj"
        "c0sKYlg0WHdVbXoyZjNQK2dEK0xENVlDMkIycFpFbHl2VnJJUnIxZEU3U3RCS1NEWi8wT0VvbFV2dDVnd1M0T0FScQpzMXRy"
        "RWdvckJnRUVBWmRWQVFVQkFRZEFIV1V6RjROWCtmRm1Fazc5aUQ2NzJUbDIrNXliOEg3SGszd2R0TE5LCllURURBUWdIaUpR"
        "RUdCWUtBRHdXSVFSTmYyU1V1dlNFTHBqS3FXblpuc3RXWEN3SVlRVUNhck5iYXhzVWdBQUEKQUFBRUFBNXRZVzUxTWl3eUxq"
        "VXJNUzR4TWl3d0xETUNHd3dBQ2drUTJaN0xWbHdzQ0dGZkZBRUF5anYrNVpWSAovbWxYNm1GbzNreDlEcC9aWnBUSExYUUdz"
        "d1B4YkwvZEh3MEErd1p5Um5STFRlUnJUWndoU1JwZW9lWVhJSHQrCkE2WEgySDVEaWdKd3BLNEcKPW4vQVcKLS0tLS1FTkQg"
        "UEdQIFBVQkxJQyBLRVkgQkxPQ0stLS0tLQo="
    ),
    "pgp_rsa.asc": (
        "LS0tLS1CRUdJTiBQR1AgUFJJVkFURSBLRVkgQkxPQ0stLS0tLQpDb21tZW50OiB0aHJvd2F3YXkgdGVzdCBrZXkKCmxRT1lC"
        "R3F6VzNVQkNBREJGbytqeldZUWwycVptWHlJODE0amZ0ZE0rZjBMR25ZRFlUUmplK29IdU9HdGZoSDIKWlJGaTlJWjkrQW1W"
        "c1dPaWhMenNHei84THVsYUljV3ZKbmh2OGRINFgyVkRENG1IVmhOOTVlUnp4MGhPRmplUQpueWV3VUNnTEZVc2lQQW9rZmZv"
        "RldiZ055Sk1acFUyTng4eFkzbWUzaVF2clA3MEZzZVFpOVhDQXRwZVI5VHB2Cld2eE1GSHZqd3ZzdVJ1L0FjVXRuelYyV0FW"
        "YndIRzRST2tlNEp5UTM4UEQ3bW1aR0FvUHdQWFI5a0xEUmJidlUKdjF5Y2ZyajNZNWY4dDU0ZXlDdjRKcmNnZGhDY29PMUk0"
        "eXArUGVrZmZaaktrL09Pb1V3dGg3WXFMcDZiWHlRZgpMSWVFanlyYmdjeGR4eGIrT2I1VmttTVdHY1RuQkdjS0JoaGhBQkVC"
        "QUFFQUIvNDRCMXpzOGlnZ3ZsOC9iT3RYCkxnOXVDMXRjU2Rva2c2d2s5T3JueDBnMHIzQkZFS1VUczJZbEtjRnhBaTE5MDNp"
        "TzZ5ZUs5NmxNZXl4WmJCMVoKNHJibC9PeXB2cnk2aGVLcGM4KzZJNkJ6L0NxK0JmSmZzOThuYVVzRlZFdDJCcWdHeU10cERB"
        "eTlheXRNTU14ZApUTkcrSStOQ3ZiREl0YmthMHZEWk9CRktONi84UXNvWDh1VVl2d2RjS2VnVVk5WkpuQmxtcFh5cXR1MElT"
        "RWlpCjlrL1lvekE1V2pYdGZuTlAvMmwwQVdnYkI0czJSS3BENFUySjdIaFgxdTNWMkRqN3RjWk5rMXNMU3BVektXRmQKSEk3"
        "YTR3Sko1Nm10Sm13Q2dJaEVaQ2RLOFRQcEJXcXdJdXRNNW44bnlCbXVWU01xL1lQZmlSc1h4bzMwNzdDUwpBelkxQkFESkk0"
        "WWdYMmY5ak1Zc1Q4RDZPUjZ4cFRJUmVUbUhzZmFMeWMxSjBuaCtrN2lCUmQxLzVNQ3B2KzNxCnBITlNzeFQyUklUUUoyL0Ft"
        "bnBtWDBEK214Ullkbi9wTXpvYng5TS9jbStyZWJhK2V5Sk9QU001cFh4eUVOdjUKYXYzNDRnOGlpalZibG5DTlFqR05DQ256"
        "aS9RMjJMdjl6Q3FMN3AxTW5Jb3lUbzdxcXdRQTljRG5MTU9ZVGExKwpsVFp1c0pMKy9LMUdEUnVzN0gxN3dPcCtyUHcwRFBu"
        "b0NSSmd4bTB6clI0YlFabnZzRC9taEVNZFl3d25ieW9DCjVHRXh6VDBhSkFTQzMyUUV2RFg2TUovdS9lYnlwUiszTkt2T25s"
        "bU03ZmRaV2I5ZWNBSzR1SENCOHBFL1VTRXYKZTVOTmZSejBvWEMrL1RHM2YzcnRHMllsVXRLMENTTUVBTlVHYlY2cDl6a2xB"
        "aUJCYnV6OG9yZy9MYUpXc1BmNgpKZ2x4RytZR1dTWkNpNG9zaGxjS1hsUWdFWUYrVDk2bzNtc1RsKzRYUGJ1N3orREl1bkJS"
        "NFY1a3hPZklLaHoxCmVqUnI4RDl6b3RFdUpiZnIwWDZzeGpTNktzQXpkUVFJZllwaDN3dThBMVJPeng4WEo2WFEwZEs4WjZt"
        "NXRpc3QKU0RUWTlCT1lkVFNiTy9HMFBFRnNhV05sSUZSb2NtOTNZWGRoZVNCU1UwRWdWR1Z6ZENCTFpYa2dQSFJvY205MwpZ"
        "WGRoZVMxeWMyRkFaWGhoYlhCc1pTNXBiblpoYkdsa1Bva0JiUVFUQVFnQVZ4WWhCSGREUXFiYkhnQzlMSVkvCjNPUXZnNWJG"
        "YlhnL0JRSnFzMXQxR3hTQUFBQUFBQVFBRG0xaGJuVXlMREl1TlNzeExqRXlMREFzTXdJYkF3VUwKQ1FnSEFnSWlBZ1lWQ2dr"
        "SUN3SUVGZ0lEQVFJZUJ3SVhnQUFLQ1JEa0w0T1d4VzE0UDVvT0IvOTdSVlpnZXNlYQpEWTVLMENYMVdpc2cxbEhVbitMQ3di"
        "TkZnNmpuTHNxSGV2dExjQkxheEtsdVZNVGF4bmd1Yjh2ak1QelVDVndkClVRRFZJQk9HVHg0TmlwNmM1WTN3VzJjVkRPRi8x"
        "ZlBiaWVaUndPVVltZjA5d1E4eFlZR1pKUU15TmFHc0poOVMKMWMxb3A3dGo4dlRtb25kclVLYVk4Q0xBSkY1Q05WeWZxeGtI"
        "YmhYQ3RCem4xRURoalFNMjBHVnJZM01JenM1dwpUdEFCUWZyTUZJdEg1SWs1TUg1RXJiZE1TeWFQTm1jbGNwL3d0eTRUb0s5"
        "NDZtS3NBYmowamNwQ25FWHdNVmU0CllTTE5qQjRYVWkrdVNFZHBxNHVGcWw2SWo4TFlreDNPUHZ2aU1GR2V3NXRLN2hXWmJ0"
        "Wk85RjdkYUN6bnZVK2gKT2VpYjRwU29mSnh3Cj1JU0lDCi0tLS0tRU5EIFBHUCBQUklWQVRFIEtFWSBCTE9DSy0tLS0tCg=="
    ),
    "pkcs8_ec.pem": (
        "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lC"
        "QVFRZ2REcmVjTVN5ZDZXSzhzb1QKOGdsQi9Ia0NDbVJTVmx0elVPQ0k1dWQ5d1I2aFJBTkNBQVNSZUxkSFdtUDZnTXU3OSs0"
        "dDEzdnRnNUxwWHlrQwpmaGd5dThJa2prdlUyVGh5TXFmajVNOFlVMU1tNmlmN29vWEFmWWhDUzFIZHBVVVpWTzZQb3VRZAot"
        "LS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg=="
    ),
    "pkcs8_rsa.pem": (
        "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VB"
        "QW9JQkFRQzR6OXFaZUcrVjVVMXQKNmZ2aXh3RVh6M080NGFuajFCNjNhenFCV0tJemRCRy9XaGFkckpDOVl0S2QwU2w0SEpp"
        "b3BFM0E1THR4ZFFRRwpXVUh6bzUyeFVPdDQ4RjRUZzBlRFZYRVo2ZzIvNUcrejA2VkZWREN4Wkp6VFJCbWxaMGdOdy9lZDB4"
        "T2YvNnNoCnVsTUxPQVRVTk5vc3ZadG0vMEdaQSs0MnlrMW9aRW5JY09KVnB3cjlOSC83ek9URzhVZWZtZExNUXBuNlpveWEK"
        "OEU5YTVXc1RMQmpxSE5xVFVRSTdDOW41UnJOUk1NbTA2YkY1RW5UM0VkQXNKZGxGeTZ3d1pHWDJkeHFFZUllQwpJVElUZ2lY"
        "RCthWFFaNk9mMmhuZUlaTmdFSkh3SnpoTk9CNzhTVjN3ek1jaHZFVU55dnNIQ21acnBBcnZlaEIxCkJvL2ZqWk9qQWdNQkFB"
        "RUNnZ0VBUngzYzdiKzFtTVhqTk0rY1dSamhKOHR4cVl4VTl0SFNmQnhzS0FmMmFyeFkKYy96enhQcjV1NWNDbXk0NHVmcXZG"
        "LzRaMllkclJlNlVmT2p1QXhaTUFVYTFSaFdnN2Z0UGtvOVhkWFJtbEJnUQpqKzk2b3FJU0ZzRXp3K3hwdmdkdlo3U29YWGd6"
        "RGhleFA4cFdXSFBYRDkzQ3N3TEhnU3ZxanpvKythQ0JoeENoCkNJRHFhTUVZYmlWUkF1OHl2WkFqc0hGbTV6QVcrN1dtK3ZB"
        "bHo2SVVYSUNBVit1QmxINlFKOTRWSk5xQU9vdkIKOEN6ZFBSVUk5SkEwRWtXL2FuYmJ5YmdVSEkzakFaVnMyOXZXSjV4aHJU"
        "QzdPcXB5RHJpOVdQTXQvditsOWRscwp2ZndKM3d0b1JUdHZMVHcrM1B1YldpYUgvbDNTQitIZzhTcVZ4SHc4U1FLQmdRRGZs"
        "SDNSak1LSWlpOEFzWGYwCmlpNEZVQ3Vpdzk2RWJnc0Zqb2JJY3B2d3FHdzBJOXZHR0h0N3NoWGhVTjNkblA4SkNLS0M1bG9O"
        "bTFlNzdpLzcKQ0pMa2ROUCtOV20zWENmcEdUNVdYU1cxRGd2S3JDTVlPckVXTi8vNDNQODc2U2hkK1B1NDJiNU1SUDFvVEsw"
        "egp3d2xZbU1sMHBQcStIR2VrbDZJYk5MdVpCUUtCZ1FEVG5FQ1hHTlBFd1BHVzRRQ0pHRDJKVFEzY1RQdGFrVVk3CjFVcGkw"
        "cENZd0s0S0d4YWFVbDdWSVdNUW1FQ3FoK2ZFUkdKQUtsMU92dnVFUVJ2dGUrR3hDZ1hxZG8yMktIWjYKVWR0QlJQS2trUk9h"
        "aHFwYU8xYi9lRWlkWE5VTW1YdFc4eHpYT2l3UDJQdytnN3Y2NEVtQTFVU2JoZnNGdXJodgpEOXV6ZXozNmh3S0JnQmJrSnpX"
        "clNjZWREazd0M0xCRzdZdFJ1QVlFTStZdk5pV3RnQk5KMkxsOUpRYjVuT2pkClhOYy9Wb29wTTI0YlF1bHozdCswSWdnK25X"
        "NzZaaU0zcjRLQWk2djlZQU9NQmZJUnlaWWlGMWhBUmVqTVV4T0oKL3RPZGpERzR2dEV0Z0JxUEFZYmRsR1JPcy90WHptdjhU"
        "aHFxR2dZOVZnYmM5YWVlZHRSK1E2N1pBb0dBQkordAphWi9KUU10V2ZBMStqWUJTRitYdkg1a3ZCTk9YelViajBUVDRvOTNS"
        "NzdhWHo5ZHM2d3RIdHQwY3pKMGJtMVpECkwxTzlwakxXSEJXd0hvaE9iaWZoNlRXZDh4VC9RYno0Slh6ME1GUmJNVTB2Kzdq"
        "QU5lVFM4VjFONm5DUUdWNUcKaXcxaVdSWk1yTEVFTW44a0hBU004emtDT3lYUlVkdnUyUVVnWFpFQ2dZQW1ieEtWTWtwUm9D"
        "Y1pZQkZkTDdrcwpqemNJYWFBc3ZqN1lGNCtTaEExTzlTNWtJMmJuZmJFV2JVQ0Q1YzNwSTJicG8yaXRhbWdZaVpRbS83bStK"
        "RzhpCmJRaFYrZDcrcGtMTmhGUzBidWJkZEZ4MGducXBTaWZrRVpncHVJZjk3VnlzcHJSanJlZk5GZjkwTndhZFVnc3QKMEtm"
        "Mk9xcThDbSt0SitKTkVoVXMvZz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K"
    ),
    "pkcs8_rsa_encrypted.pem": (
        "LS0tLS1CRUdJTiBFTkNSWVBURUQgUFJJVkFURSBLRVktLS0tLQpNSUlGTlRCZkJna3Foa2lHOXcwQkJRMHdVakF4QmdrcWhr"
        "aUc5dzBCQlF3d0pBUVFwRmhXTk4wOWg1ejJPaXpjCm9jNHZrd0lDQ0FBd0RBWUlLb1pJaHZjTkFna0ZBREFkQmdsZ2hrZ0Ja"
        "UU1FQVNvRUVNL3V2TS92UDBCV0kzQnoKNkVWRE4xZ0VnZ1RRVEd4bGJUd3ovcWk3Vk1hL3FPTDhkNVdsL0YrU3F0VmRBZkdQ"
        "eXQvSUlnR0ZveGNiVUl2MApVeElLQVRzcitLQ2gxeTJ0OXlkTzBrK1ZUbDJNQjNPYjJwN2liUCtPOWUrYjU1ZElLRi8xckph"
        "cFNFSWxlVkZnCjE2V2lBbmo3Rlo0Z3dzekFZM1BEeXV5M3RETGZUUWNpRUNVMTlWUU51WTVTaFUvWUROOWRvcGZvbThiNER5"
        "OGQKWWVYcWZ6Q3M2V2FrRG91TnRTOVlBd0RUc21NaUIwM1J4aXcwTDZ6ZVRQUnNLWmlTUGRtWFZIUVIwZXJ5MDdLUgpWYjhI"
        "aTJHMXltTkpybGlWZ3VabXAzcEhtYVpUZU5XNGxpTFZjRzlBVC92ZnNMdnJzVElqNE9aMk5ZR2lhc2NZCnhmWlVQRnBvRmNQ"
        "WUN3SU10Zkt6K3h0VWVwOUdlVENoQkk0WlF6djFveXZ3TmdRemgxZVF3Nnd4THdjN0dKcjQKc2ZEYXJUZzBxQWEweis5WERk"
        "NmJiZmhiT0xSdlFKbk15VFMrMFVlc2xURWtJMzRiOHpwa1dsWUVhMHNaeDE0RgoyZi9hVDlRVEs3Z0VycGRRNkd3MlJzcmwz"
        "eml3R2doeHd5QzJ0RlVDZHJXdU01bXI4RmpuZjVWQmNuRlRsNzNUCkVQTVFLb1lRKzRUbzIzVjFhTWVtYmJGZXlVTTcyTVB1"
        "a0xXVTB3NWZEeGNsYXFPNzB0Mm1Ka05wRzNwRVFqV1IKUXhjMnRjSE9ZRmM5enBYWDZaa0R3ZkdXRDh0dHRFU1RKdkc5Zk50"
        "Ri9iK25kcmlaSElQRWZuQ1kvdDRZTU55OApINndnMzU2UnFDbExJQVVxb0NSTlpHTmZ4cGlZNXZ5bzRlWFFTdUV4RU9sb3M4"
        "QWg0VSswYUxYU2xZUEZKYUpiCi9MKzVMeEZmZTdoaXVVTjlraVZJTDUzbjVDc1krWEJqTjZOaFN3UFRLaHV0RXc0cHFFNDNs"
        "ckFMdUxtdVJKa1UKUlR5WktaeUNaVnJVSDNjQUJibWFyR2ltdStQODQ4aHdVTlZzZjNValJFVllKOEVjeitYRHlnMHVocU5m"
        "MFEwWQpzRkRyL29SSDFEdTZNVnFQKzNCcysrYkFabUt5dE5MTXMrdjF6eWtwNFVkcUdreGpHMUtEdWJSaW1Nd2VYUndrCngy"
        "Zkg3WkM1d01YcEttV3NEL29WaGRodVVzT3ZFUW90SjUwRTc1disvaHFkQlZrYXdtcTUvdkJGMmtRSnZBR3YKZVVqRVAwZDhv"
        "ZFhubk1FanRvWWEyZHpGNFFiN2dsZ2Jpa0hVNy96NGV4RTBlRHBUNTJCWG1KeUJrcnNYNVltYQozTGVuNnJzSlRoZ0JWTTBW"
        "eGZKRGpYYVVEOGZIVTB2YnI3Z2dIVThqR1dBMDRid2psRWFjakhibHZ2dlllRExRClF4T3ppQmVWWFpuWEFqWklLWEM0eURQ"
        "SkNjbEd0L2J4NVN0Z3VEUFRHOXpUejdhQzZXb1ZSbVFndFJCaGoxV1EKQ0xobzlGUkdYZzkrNGRsVHplRmxjRTAwd0V0VjBK"
        "QXRDNmJsbXpyRGp1QmFVN3FZdEFqZHc3WGpqcXpjd2pEOApwNnhaMWd6S0JDcjlFb0xTNGdCcWhjZnJ0Y1hGekxBTEVZLzBB"
        "YnNTYmptWGxyM3FKaVY0QTJ5UmF1bkZPU01jCk4xNXQyeXBWQytmclY4ZG5NQXN0YmpIZjlURkJ0aHZMWWxNbFFHYW5nOStQ"
        "V2wxQTl3b2VaNzM2NnN0UEwxM3AKenNwc2tsQnFHUmJlQjl2ZHZkcDh2UTRyeW8xYUVtdnd5QzFNd2Zac1UzMWg3MjFqTnBo"
        "WkhSY2dwWGxHVGMrKwpSV0JqdmRsUlZONE05Ri9UcW1wdDVlWkpueVpDTkxQTzUzTXd5UHJuR3grcGpZSUthbzRURm9EMDdX"
        "endZUXZmCllPK3kvbVZiTnQybUZqTEhQaXZab3k1VTlTZ3VWMlc3M0MzdEZuSDBHOWhYK05oYzlaVmJZdmJMZTViS2ozcS8K"
        "eVR6SGJEQXZYUGw5eEZFYzMyMTRNOW1kRSt6bDcyckRjRzBCU3pXY3lHSDkxR3lIK2UzdGVqTUQ1WlZVUG1vbQpQWldKaTRl"
        "RzMvcE9wUUVtbjVXRGtMSzlqMFFhOXM0c3JnU1VhQmtobW14RzJINmxJR3RKTExrPQotLS0tLUVORCBFTkNSWVBURUQgUFJJ"
        "VkFURSBLRVktLS0tLQo="
    ),
    "putty_ed25519_v3.ppk": (
        "UHVUVFktVXNlci1LZXktRmlsZS0zOiBzc2gtZWQyNTUxOQpFbmNyeXB0aW9uOiBub25lCkNvbW1lbnQ6IHRocm93YXdheS1l"
        "ZDI1NTE5LWtleQpQdWJsaWMtTGluZXM6IDIKQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUQ5RnJOUVNSSkhRdmZCdWlpSEFa"
        "aTlUeEVOaHRJVjJ0T1ZFWHMzQgpVYWNJClByaXZhdGUtTGluZXM6IDEKQUFBQUlMaFFWYUlqRFR0eHJicGVuNmEzK3hPOXhE"
        "clBkdTU5cW9xdlN2Sy81Qm4wClByaXZhdGUtTUFDOiAwNjVkMWY0MTJjZTMxNzc3NDliNGI2YzBiYjFkOWM0OGUxNDczMjk4"
        "NTMyOGQ0NDhkZTFiMTljZTQyY2Y5NjViCg=="
    ),
    "putty_rsa_v2.ppk": (
        "UHVUVFktVXNlci1LZXktRmlsZS0yOiBzc2gtcnNhCkVuY3J5cHRpb246IG5vbmUKQ29tbWVudDogdGhyb3dhd2F5LXJzYS1r"
        "ZXkKUHVibGljLUxpbmVzOiA2CkFBQUFCM056YUMxeWMyRUFBQUFEQVFBQkFBQUJBUUNiZnZTSDlTbFFMUlhTTkNNaWZoOU5C"
        "TzdMRVNGSWZaK28KTDZnckljRmdyU2gzZ2QwM3ZDTmM1WHpnTlN6ZW9HSUhzQnpGZzZ3ZXRlNkNEWU1FRHJhMVAyTEo4bWpy"
        "aFdzbQphckFSdmY3Sm5IMkdWTzJWNkJ4RGdJemtmelRubnpNOWNZT25sU2JlWW1xRGd5YzhzN2xVTTQrbzBXQVBQbFhuCjBB"
        "aithanJ5OWlRYnkrUHhOMm1xL2lFZHVud0xLV0hhN2Vuckh3OWlmWmF0UDJpbmVaRzZETlpCa3hJQUE2aXIKMUpwSHFOR1ZI"
        "UDc4cSsrYnBzbW1qSWZqV2IrNDI4WVhXSlY1SWMxRFIwT2NuWDZvZVhEdVAyTGRZdS9MT1FPZApVakM4ek04WlZrRGhzVVdJ"
        "TXVNZUtvUFNacW51RUc2TEVxNHp6WkdCM0hhL1NKN3hjSVZaClByaXZhdGUtTGluZXM6IDE0CkFBQUJBQ2M2c2txU3FXZVcy"
        "RWg5NnRkSzVtNng3ZVRCWDVwQVIwVlJNS1loRC81cDhTbWxVOEE1OE5vQTg2NUUKL0JyMmI0VHRBM1U1TVBWV2hPTytzTzBY"
        "SVRVODFwbUlWTHdHbnUvRVBzTmJJYXFQbG9PTGJaMUNQODh2NFZ2TQpVL2FUallQVTNaZ3I0dkI3OTg5U0NWWWhLWUo2dDZX"
        "cG5RaDdlNFRPVVZhT1NtejlFNVVNRktGU0hnbnF2K2ZsCmt2ejB0NkRNR1YxVHA4STlpbTVxZXFGTXVDTG5LR2FMVXg1ZkVq"
        "V0JRQVRtK01GaGNxSk9ZVFBlVWs1ZDdsK2gKZUI5MEE0S3BacXNWQ2doVVNUYkM4Z25iK3FkS21pb2JneUN4eXVVSlZEOEhI"
        "RE5aRUNlSG1ST2lrems0Q1FuTApNeFk4WUVTaXp1WWo4Nlp3Z0luNllhdEw1Z0VBQUFDQkFNb0lUcklhTTdZeGtVS0RjejdF"
        "d0gyTVI1LzVQUUI1CmdZV284RDNacHlXNG1hSGhyOXMrSGtDY0VVTDJoVXl5dXk5T2xxUkVmckxKdU91aWlkM2liVmFtMlB0"
        "Y0hNSjAKWDU0WWdBM1lKVjRsWU9haXo3TDhpL2VFZVBwS2E2blM4UVNreDdMVWxZQW5ab29vVkN4dlFWTFlJV3BZeWdmQwpT"
        "R3hHL0h2Z2RQRjVBQUFBZ1FERkNGQzdWeVJwWHZlNTNjc1V1MUFVSUlPQ3p1ZjB2cm5wWVdGajZOMmo5OHlsCmg5NmE2R0p3"
        "c1RzUW5qcmZoSXpxbC8wR01EMDByRFNkN3FFZ2FCaDlCZldvR2t5V3FhV3g2dHYrLzl5WXdjb08KU1duQkY4MzRrMGxhZkh3"
        "SlZndUFpblRSNm9ZV0k2Vy9leCtUVGZQRHhQcXZvcHhVZXR4OHdvS0ZCTElhNFFBQQpBSUVBdzVBVDU0N1o4UGZldG1QYjFs"
        "MFNvdUh1UEU0ZnQzMEFWM2NUNHExTGR3YVhKQ0JwaW9ydHRWaGMzS3hICkRYdlhiU2M2d3BJa2ZBY2Q0OU9EUHJOZDNPd2E0"
        "cE9jc0FnMkVsOHY0dTdSMEFDanFDU3ozZlpLVnBGL09wZm4KRlR3RDJVdkw0ZUpveUpuUmFDUnVxdU1iY3UwMktoRVJQNVVy"
        "eVB2SGhacEFyQW89ClByaXZhdGUtTUFDOiA5ODVjOGU4Y2RiZWY2ZmFkMDc1NDI3ZDEzOTY2MjBiYmYwOTZjMDE4Cg=="
    ),
    "traditional_ec.pem": (
        "LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUhRNjNuREVzbmVsaXZMS0UvSUpRZng1QWdwa1VsWmJj"
        "MURnaU9ibmZjRWVvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFa1hpM1IxcGorb0RMdS9mdUxkZDc3WU9TNlY4cEFuNFlNcnZD"
        "Skk1TDFOazRjaktuNCtUUApHRk5USnVvbis2S0Z3SDJJUWt0UjNhVkZHVlR1ajZMa0hRPT0KLS0tLS1FTkQgRUMgUFJJVkFU"
        "RSBLRVktLS0tLQo="
    ),
    "traditional_rsa.pem": (
        "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBdU0vYW1YaHZsZVZOYmVuNzRzY0JGODl6"
        "dU9HcDQ5UWV0MnM2Z1ZpaU0zUVJ2MW9XCm5heVF2V0xTbmRFcGVCeVlxS1JOd09TN2NYVUVCbGxCODZPZHNWRHJlUEJlRTRO"
        "SGcxVnhHZW9OditSdnM5T2wKUlZRd3NXU2MwMFFacFdkSURjUDNuZE1Ubi8rcklicFRDemdFMURUYUxMMmJadjlCbVFQdU5z"
        "cE5hR1JKeUhEaQpWYWNLL1RSLys4emt4dkZIbjVuU3pFS1orbWFNbXZCUFd1VnJFeXdZNmh6YWsxRUNPd3ZaK1VhelVUREp0"
        "T214CmVSSjA5eEhRTENYWlJjdXNNR1JsOW5jYWhIaUhnaUV5RTRJbHcvbWwwR2VqbjlvWjNpR1RZQkNSOENjNFRUZ2UKL0Vs"
        "ZDhNekhJYnhGRGNyN0J3cG1hNlFLNzNvUWRRYVAzNDJUb3dJREFRQUJBb0lCQUVjZDNPMi90WmpGNHpUUApuRmtZNFNmTGNh"
        "bU1WUGJSMG53Y2JDZ0g5bXE4V0hQODg4VDYrYnVYQXBzdU9MbjZyeGYrR2RtSGEwWHVsSHpvCjdnTVdUQUZHdFVZVm9PMzdU"
        "NUtQVjNWMFpwUVlFSS92ZXFLaUVoYkJNOFBzYWI0SGIyZTBxRjE0TXc0WHNUL0sKVmxoejF3L2R3ck1DeDRFcjZvODZQdm1n"
        "Z1ljUW9RaUE2bWpCR0c0bFVRTHZNcjJRSTdCeFp1Y3dGdnUxcHZydwpKYytpRkZ5QWdGZnJnWlIra0NmZUZTVGFnRHFMd2ZB"
        "czNUMFZDUFNRTkJKRnYycDIyOG00RkJ5TjR3R1ZiTnZiCjFpZWNZYTB3dXpxcWNnNjR2Vmp6TGY3L3BmWFpiTDM4Q2Q4TGFF"
        "VTdieTA4UHR6N20xb21oLzVkMGdmaDRQRXEKbGNSOFBFa0NnWUVBMzVSOTBZekNpSW92QUxGMzlJb3VCVkFyb3NQZWhHNExC"
        "WTZHeUhLYjhLaHNOQ1BieGhoNwplN0lWNFZEZDNaei9DUWlpZ3VaYURadFh1KzR2K3dpUzVIVFQvalZwdDF3bjZSaytWbDBs"
        "dFE0THlxd2pHRHF4CkZqZi8rTnovTytrb1hmajd1Tm0rVEVUOWFFeXRNOE1KV0pqSmRLVDZ2aHhucEplaUd6UzdtUVVDZ1lF"
        "QTA1eEEKbHhqVHhNRHhsdUVBaVJnOWlVME4zRXo3V3BGR085VktZdEtRbU1DdUNoc1dtbEplMVNGakVKaEFxb2ZueEVSaQpR"
        "Q3BkVHI3N2hFRWI3WHZoc1FvRjZuYU50aWgyZWxIYlFVVHlwSkVUbW9hcVdqdFcvM2hJblZ6VkRKbDdWdk1jCjF6b3NEOWo4"
        "UG9PNyt1QkpnTlZFbTRYN0JicTRidy9iczNzOStvY0NnWUFXNUNjMXEwbkhuUTVPN2R5d1J1MkwKVWJnR0JEUG1MellscllB"
        "VFNkaTVmU1VHK1p6bzNWelhQMWFLS1ROdUcwTHBjOTdmdENJSVBwMXUrbVlqTjYrQwpnSXVyL1dBRGpBWHlFY21XSWhkWVFF"
        "WG96Rk1UaWY3VG5Zd3h1TDdSTFlBYWp3R0czWlJrVHJQN1Y4NXIvRTRhCnFob0dQVllHM1BXbm5uYlVma091MlFLQmdBU2Zy"
        "V21meVVETFZud05mbzJBVWhmbDd4K1pMd1RUbDgxRzQ5RTAKK0tQZDBlKzJsOC9YYk9zTFI3YmRITXlkRzV0V1F5OVR2YVl5"
        "MWh3VnNCNklUbTRuNGVrMW5mTVUvMEc4K0NWOAo5REJVV3pGTkwvdTR3RFhrMHZGZFRlcHdrQmxlUm9zTllsa1dUS3l4QkRK"
        "L0pCd0VqUE01QWpzbDBWSGI3dGtGCklGMlJBb0dBSm04U2xUSktVYUFuR1dBUlhTKzVMSTgzQ0dtZ0xMNCsyQmVQa29RTlR2"
        "VXVaQ05tNTMyeEZtMUEKZytYTjZTTm02YU5vcldwb0dJbVVKdis1dmlSdkltMElWZm5lL3FaQ3pZUlV0RzdtM1hSY2RJSjZx"
        "VW9uNUJHWQpLYmlIL2UxY3JLYTBZNjNuelJYL2REY0duVklMTGRDbjlqcXF2QXB2clNmaVRSSVZMUDQ9Ci0tLS0tRU5EIFJT"
        "QSBQUklWQVRFIEtFWS0tLS0tCg=="
    ),
    "traditional_rsa_encrypted.pem": (
        "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpQcm9jLVR5cGU6IDQsRU5DUllQVEVECkRFSy1JbmZvOiBBRVMtMjU2"
        "LUNCQyxFRDcxNzY4N0ExQUI2MUFCQzExRUVCMzc5RDE5ODlEQQoKN0hVUkFvd2lVdWJ2cXF5S0xCanRXdHlFN3U4SFNyRk1q"
        "azMwR1RhZUdwZHJrQ1Q5Y0w4RWJJaDBLdHJCN0hOegpRckYvKzVEd3M5L3JnelBKVTJvRmdrSzdPbHZMdDhaQUlKcWZIbkF5"
        "T3JZK29Ma1ltRk1McmYvMG1rcWdHd2NYCk9NTGpKMGtxK3ZGcVRZRzlXREM5VmlaOG53MU1PcEtQWDArOTlkZzJ0VGx2NDlr"
        "YTFsL2QrTGtGWU1OUDNnekIKMG93cFY2TGRCSndGRDJxaUwydE1hYmo3T0pwTUxidWt2eHlRenNpV1dSSmlWa2RQczBpZVNB"
        "aVoyK3BxRkhucAp4QnhoRlBEQm80ak1nRDg4b1VmdHhjWDYwNUUrSlZwZG1wNm1ta2M2cmZsYXNlVHNzNXNmYzhNcmM2QUNY"
        "azZHCnBNR2E1K2JCT2lQRnVWZTlBNU1hOWI5N2VJK1ZoaDZBWDVWNDYvUndGd0VuUkJ5YmdxN0VXeU80ZENhd3F0QVIKT1Ey"
        "Ni9FZ0ZIL2J0UmNNVUZDcTJ3UnVNWUZiODdLSDA5cVV5dlpZRE51Y1hFdE9MSHYrKzNLZE5VOFdTUGRUQgpkRGxqWHUrRzVB"
        "NnNROVp2enRBMHdmbHNxNTd1eE9nbnoxZS90TXZ1UHNJZjd5Q0luM1kxeE5LVlVnbDJaYnBKClRvOU9YNWFXdzdXOXM4T2ZE"
        "a2VBbEZXa1JJR3BLSG4vekF4RW12UXluaUJyQXplV3dWbFJJeEUxaVhsWGI4RlQKYUhWL0JlMmFZQVIvVzY2QXh4VG0wdnFE"
        "d2d4RUhmbkxIVmY5RXp0ZE9oSlFTa21ESytkRzVIWXRRSnJIeHh4QgovNTM4c09LUlJxRStzZTB2eFp1R2lPVlNETnRIZk5G"
        "MzFlS3UrODMyblpqUjlhL3VwN1QrWDVJTmJ2eGkzSzF1CnIvb0ZNU29rYitBa0RwM3BSdjZoaGlsL2RGejAyNzh5a1pIemJP"
        "S0M1dGpVd2Z1VnplZ2loWldyaGtHZUp1MXUKRlBHYkcveFhqNUZhL1JkS04za1lVSm1YU3cwRzlZeUNEZmJ4YnF6VHB0Q2Jm"
        "RVRIMlpOdE9MNVBOSE9rc1hHVwpFWDVkUllVMVU0UEdVT1ZtUjVGc3RvWlZTNytod2Y2MGpSV1Ixd1FyaW1rWXg0RysvYThk"
        "dlQxMEZGYmd3UEgxCjl5SHdpK1Y1VTFtUyt0VlpubUpPdkZrSy90dWJrMXhvdHJZSWZDaWpERnhNeVJ2eVNGUm1xN2JFWGtt"
        "TFRmQ2MKZGR5bFhrL3llYTFjUDFZN0MyTmJBN0hmeS9SQ3k5SmhRaEtGMlRzMzFrNnhJZ2E3Sy8zbEs3R2JKVnVvNktLNwoz"
        "Q2VqMXQzTWJaN0Y0VFNGYXNESmZjUGFoSlp5Zldlejd0azBwc0E3bXl4a1pzbjZYTFROTWJZRm5uVjgrTFJkCjhkc1ZwcHBm"
        "eVlvUURZdWhvSVBYMnQwODJ2bWJZTzlYR1F6NHRGL1F0TW5GcmZQV3dyNlpMVFRvOUN2Zk1PRjUKbElqZEJCNk9NQXF5b3pU"
        "UEZzaFBwQ09OUnMxa3hhemdVL3JYVEZDeTd0ODZWN2dCZEdRWGMzU3QyRm4rRVFaMApwVDdEYXVsM25YdDNjUjBuWEFVVlRk"
        "anRFUkMwVjhvMHRNL0IrZkdlMmdlb0ZnTTFPclVuVG1zM29XSkh0K1FRCnY3T1dDUm9qMktqVE9SK0gvdWdjZGFqc1hkN21H"
        "WXBQNGtPaWNLQWtDQm9tZjdVczh4TXp1V1lrZ3QxN1o4elQKdmxKTTA5VndIMzc5VjhuQlB1cm9PbmErYzFuVWpwY0NGWDAw"
        "OTBLM0lEWlZLQ3lMbU80TkJONUwvR1p1NExuRwoxN3dNV0lXcE9yc0Q1Vy9nK2dhY1BocU1DcEljOWFoTVkwc09EaVRLNVkv"
        "UlJQZjMvUkxEVGVOTUliZ1V3enBaCmxhSEdIYTExeXdrbnEwN1hGaDZ6eUxaVTBuQU5UWlpQQXlKS2FaVk5TczBEWDlHNlRM"
        "NHV4ZXBGSlhtMjVtMTIKK242eU5qMTVhZnhkZURab2svenRUVGRlYmhTWGJjL0hhUmxTYS93Ry8wbzI1UjhGQyswNzd5VlpE"
        "czRmcVh6TQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo="
    ),
}

# An OpenPGP public key block: not a secret, and the floor must leave it alone.
PGP_PUBLIC_KEY_NAMES = ("pgp_ed25519_public.asc",)
PRIVATE_KEY_NAMES = tuple(
    sorted(name for name in _ENCODED if not name.endswith(".pub") and name not in PGP_PUBLIC_KEY_NAMES)
)
# SSH public keys, one beside each OpenSSH private key.
PUBLIC_KEY_NAMES = tuple(sorted(name for name in _ENCODED if name.endswith(".pub")))


def throwaway_key(name: str) -> str:
    """The key file exactly as the tool wrote it."""

    return base64.b64decode(_ENCODED[name]).decode("ascii")
